import os
import shutil
import time
import openpyxl
from datetime import datetime

# Define the location of the .mkv files to be organized
media_directory = 'C:/Users/UserName/'  # Replace with your desired path
# Option to create missing folders
create_missing_folders = False  # Set to True or False based on your preference // False still moves files to existing folders

destination_paths = {
'English.Premier.League': 'J:/Sportss/English Premier League/2022-2023',
'English.League.Championship': 'J:/Sportss/English League Championship/2223',
'Scottish.Premier.League': 'J:/Sportss/Scottish Premier League/2223',
'German.Bundesliga': 'J:/Sportss/German Bundesliga/2223',
'Italian.Serie.A': 'J:/Sportss/Italian Serie A/2223',
'French.Ligue.1': 'J:/Sportss/French Ligue 1/2223',
'Spanish.La.Liga': 'J:/Sportss/Spanish La Liga/2223',
'Greek.Superleague.Greece': 'J:/Sportss/Greek Superleague Greece/2223',
'Dutch.Eredivisie': 'J:/Sportss/Dutch Eredivisie/2223',
'Belgian.First.Division.A': 'J:/Sportss/Belgian First Division A/2223',
'Turkish.Super.Lig': 'J:/Sportss/Turkish Super Lig/2223',
'Danish.Superliga': 'J:/Sportss/Danish Superliga/2223',
'Portuguese.Primeira.Liga': 'J:/Sportss/Portuguese Primeira Liga/2223',
'American.Major.League.Soccer': 'J:/Sportss/MLS/2223',
'MLS': 'J:/Sportss/MLS/2223',
'Swedish.Allsvenskan': 'J:/Sportss/Swedish Allsvenskan/2223',
'Mexican.Primera.League': 'J:/Sportss/Mexican Primera League/2223',
'Brazilian.Serie.A': 'J:/Sportss/Brazilian Serie A/2223',
'Ukrainian.Premier.League': 'J:/Sportss/Ukrainian Premier League/2223',
'Russian.Football.Premier.League': 'J:/Sportss/Russian Football Premier League/2223',
'Australian.A-League': 'J:/Sportss/Australian A-League/2223',
'Norwegian.Eliteserien': 'J:/Sportss/Norwegian Eliteserien/2223',
'Chinese.Super.League': 'J:/Sportss/Chinese Super League/2223',
'_No.League': 'J:/Sportss/_No League/2223',
'Formula.1': 'J:/Sportss/Formula 1/ Season 2023',
'Formula.E': 'J:/Sportss/Formula E/Season 2022-2023',
'BTCC': 'J:/Sportss/BTCC/Season 2023',
'IndyCar.Series': 'J:/Sportss/IndyCar Series/2223',
'NHL': 'J:/Sportss/Ice Hockey/NHL/Season 2023',
'UK.Elite.Ice.Hockey.League': 'J:/Sportss/UK Elite Ice Hockey League/2223',
'NBA': 'J:/Sportss/NBA/Season 2023',
'NBA.G.League': 'J:/Sportss/NBA G League/2223',
'NFL': 'J:/Sportss/NFL/Season 2023',
'NASCAR.Cup.Series': 'J:/Sportss/NASCAR Cup Series/2023',
'Italian.Serie.B': 'J:/Sportss/Italian Serie B/2223',
'Scottish.Championship': 'J:/Sportss/Scottish Championship/2223',
'English.League.1': 'J:/Sportss/English League 1/2223',
'English.League.2': 'J:/Sportss/English League 2/2223',
'Italian.Serie.C.Girone.C': 'J:/Sportss/Italian Serie C Girone C/2223',
'German.2..Bundesliga': 'J:/Sportss/German 2  Bundesliga/2223',
'Spanish.La.Liga.2': 'J:/Sportss/Spanish La Liga 2/2223',
'French.Ligue.2': 'J:/Sportss/French Ligue 2/2223',
'Swedish.Superettan': 'J:/Sportss/Swedish Superettan/2223',
'Brazilian.Serie.B': 'J:/Sportss/Brazilian Serie B/2223',
'CFL': 'J:/Sportss/CFL/Season 2023',
'Argentinian.Primera.Division': 'J:/Sportss/Argentinian Primera Division/2223',
'MotoGP': 'J:/Sportss/MotoGP/',
'Spanish.Liga.ACB': 'J:/Sportss/Spanish Liga ACB/2223',
'WRC': 'J:/Sportss/WRC/Season 2023',
'British.GT.Championship': 'J:/Sportss/British GT Championship/2223',
'WTCC': 'J:/Sportss/WTCC/Season 2023',
'Super.GT.series': 'J:/Sportss/Super GT series/2223',
'WEC': 'J:/Sportss/WEC/Season 2023',
'English.Premiership.Rugby': 'J:/Sportss/English Premiership Rugby/2223',
'English.Rugby.League.Super.League': 'J:/Sportss/English Rugby League Super League/2223',
'Australian.National.Rugby.League': 'J:/Sportss/Australian National Rugby League/2223',
'Australian.National.Rugby.Championship': 'J:/Sportss/Australian National Rugby Championship/2223',
'Swedish.Hockey.League': 'J:/Sportss/Swedish Hockey League/2223',
'Polish.Ekstraklasa': 'J:/Sportss/Polish Ekstraklasa/2223',
'French.LNB': 'J:/Sportss/French LNB/2223',
'MLB': 'J:/Sportss/MLB/Season 2023',
'PGA.Tour': 'J:/Sportss/PGA Tour/2223',
'European.Tour': 'J:/Sportss/European Tour/2223',
'Can-Am': 'J:/Sportss/Can-Am/Season 2023',
'Frontier.League': 'J:/Sportss/Frontier League/2223',
'FIFA.World.Cup': 'J:/Sportss/FIFA World Cup/2223',
'French.Top.14': 'J:/Sportss/French Top 14/2223',
'British.Basketball.League': 'J:/Sportss/British Basketball League/2223',
'Uruguayan.Primera.Division': 'J:/Sportss/Uruguayan Primera Division/2223',
'Italian.Lega.Basket': 'J:/Sportss/Italian Lega Basket/2223',
'Australian.NBL': 'J:/Sportss/Australian NBL/2223',
'American.NASL': 'J:/Sportss/American NASL/2223',
'Moto2': 'J:/Sportss/Moto2/Season 2023',
'Moto3': 'J:/Sportss/Moto3/Season 2023',
'DTM': 'J:/Sportss/DTM/Season 2023',
'GT.Series.Endurance.Cup': 'J:/Sportss/GT Series Endurance Cup/2223',
'GT.World.Challenge.Europe.Sprint.Cup': 'J:/Sportss/GT World Challenge Europe Sprint Cup/2223',
'German.BBL': 'J:/Sportss/German BBL/2223',
'Chinese.CBA': 'J:/Sportss/Chinese CBA/2223',
'UFC': 'J:/Sportss/UFC/Season 2023',
'WWE': 'J:/Sportss/WWE/Season 2023',
'Boxing': 'J:/Sportss/Boxing/2023',
'United.Rugby.Championship': 'J:/Sportss/United Rugby Championship/2223',
'Dakar.Rally': 'J:/Sportss/Dakar Rally/2223',
'ROH': 'J:/Sportss/ROH/Season 2023',
'NJPW': 'J:/Sportss/NJPW/Season 2023',
'WCW': 'J:/Sportss/WCW/Season 2023',
'ECW': 'J:/Sportss/ECW/Season 2023',
'Greek.Basket.League': 'J:/Sportss/Greek Basket League/2223',
'NWA': 'J:/Sportss/NWA/Season 2023',
'SBK': 'J:/Sportss/SBK/Season 2023',
'Impact.Wrestling': 'J:/Sportss/Impact Wrestling/2223',
'Australian.AFL': 'J:/Sportss/Australian AFL/2223',
'Norwegian.1..Divisjon': 'J:/Sportss/Norwegian 1  Divisjon/2223',
'English.County.Championship.Division.1': 'J:/Sportss/English County Championship Division 1/2223',
'English.County.Championship.Division.2': 'J:/Sportss/English County Championship Division 2/2223',
'Indian.Premier.League': 'J:/Sportss/Indian Premier League/2223',
'Australian.Big.Bash.League': 'J:/Sportss/Australian Big Bash League/2223',
'South.African.T20.Challenge': 'J:/Sportss/South African T20 Challenge/2223',
'English.t20.Blast': 'J:/Sportss/English t20 Blast/2223',
'ATP.World.Tour': 'J:/Sportss/ATP World Tour/2223',
'UCI.World.Tour': 'J:/Sportss/UCI World Tour/2223',
'Electric.GT.Championship': 'J:/Sportss/Electric GT Championship/2223',
'Bellator': 'J:/Sportss/Bellator/Season 2023',
'AMA.Supercross': 'J:/Sportss/AMA Supercross/2223',
'Pro.Motocross': 'J:/Sportss/Pro Motocross/2223',
'Arena.Football.League': 'J:/Sportss/Arena Football League/2223',
'Indoor.Football.League': 'J:/Sportss/Indoor Football League/2223',
'Welsh.Premier.League': 'J:/Sportss/Welsh Premier League/2223',
'National.Arena.League': 'J:/Sportss/National Arena League/2223',
'Israeli.Basketball.Premier.League': 'J:/Sportss/Israeli Basketball Premier League/2223',
'Turkish.Basketbol.Super.Ligi': 'J:/Sportss/Turkish Basketbol Super Ligi/2223',
'Russian.VTB.United.League': 'J:/Sportss/Russian VTB United League/2223',
'Adriatic.ABA.League': 'J:/Sportss/Adriatic ABA League/2223',
'Lithuanian.LKL': 'J:/Sportss/Lithuanian LKL/2223',
'NCAA.Division.1': 'J:/Sportss/NCAA Division 1/2223',
'UEFA.Champions.League': 'J:/Sportss/UEFA Champions League/2223',
'UEFA.Europa.League': 'J:/Sportss/UEFA Europa League/2223',
'FA.Cup': 'J:/Sportss/FA Cup/2223',
'Copa.del.Rey': 'J:/Sportss/Copa del Rey/2223',
'Coupe.de.France': 'J:/Sportss/Coupe de France/2223',
'DFB-Pokal': 'J:/Sportss/DFB-Pokal/Season 2023',
'Formula.2': 'J:/Sportss/Formula 2/2223',
'Formula.3': 'J:/Sportss/Formula 3/2223',
'IMSA.SportsCar.Championship': 'J:/Sportss/IMSA SportsCar Championship/2223',
'V8.Supercars': 'J:/Sportss/V8 Supercars/2223',
'UEFA.Nations.League': 'J:/Sportss/UEFA Nations League/2223',
'Rizin.FF': 'J:/Sportss/Rizin FF/2223',
'Cage.Warriors': 'J:/Sportss/Cage Warriors/2223',
'Invicta.FC': 'J:/Sportss/Invicta FC/2223',
'ACA': 'J:/Sportss/ACA/Season 2023',
'ONE': 'J:/Sportss/ONE/Season 2023',
'African.Cup.of.Nations': 'J:/Sportss/African Cup of Nations/2223',
'Colombia.Categoría.Primera.A': 'J:/Sportss/Colombia Categoría Primera A/2223',
'Confederations.Cup': 'J:/Sportss/Confederations Cup/2223',
'Copa.America': 'J:/Sportss/Copa America/2223',
'Copa.Argentina': 'J:/Sportss/Copa Argentina/2223',
'Copa.Libertadores': 'J:/Sportss/Copa Libertadores/2223',
'UEFA.European.Championships': 'J:/Sportss/UEFA European Championships/2223',
'FIFA.Club.World.Cup': 'J:/Sportss/FIFA Club World Cup/2223',
'Coupe.de.la.Ligue': 'J:/Sportss/Coupe de la Ligue/2223',
'International.Champions.Cup': 'J:/Sportss/International Champions Cup/2223',
'Coppa.Italia': 'J:/Sportss/Coppa Italia/2223',
'Supercoppa.Italiana': 'J:/Sportss/Supercoppa Italiana/2223',
'Taca.de.Liga': 'J:/Sportss/Taca de Liga/2223',
'Taca.de.Portugal': 'J:/Sportss/Taca de Portugal/2223',
'Supercopa.de.Espana': 'J:/Sportss/Supercopa de Espana/2223',
'UEFA.Super.Cup': 'J:/Sportss/UEFA Super Cup/2223',
'Venezuela.Primera.Division': 'J:/Sportss/Venezuela Primera Division/2223',
'League.of.Legends.World.Championship': 'J:/Sportss/League of Legends World Championship/2223',
'Fortnite': 'J:/Sportss/Fortnite/Season 2023',
'WNBA': 'J:/Sportss/WNBA/Season 2023',
'WTA.Tour': 'J:/Sportss/WTA Tour/2223',
'_Defunct.Basketball.Teams': 'J:/Sportss/_Defunct Basketball Teams/2223',
'_Defunct.Soccer.Teams': 'J:/Sportss/_Defunct Soccer Teams/2223',
'Moroccan.Championship': 'J:/Sportss/Moroccan Championship/2223',
'American.NWSL': 'J:/Sportss/American NWSL/2223',
'_Defunct.Motorsport.Teams': 'J:/Sportss/_Defunct Motorsport Teams/2223',
'European.Cup': 'J:/Sportss/European Cup/2223',
'UEFA.Cup': 'J:/Sportss/UEFA Cup/2223',
'Football.League.First.Division': 'J:/Sportss/Football League First Division/2223',
'Football.League.Super.Cup': 'J:/Sportss/Football League Super Cup/2223',
'League.of.Legends.Pro.League': 'J:/Sportss/League of Legends Pro League/2223',
'League.of.Legends.Champions.Korea': 'J:/Sportss/League of Legends Champions Korea/2223',
'League.of.Legends.European.Championship': 'J:/Sportss/League of Legends European Championship/2223',
'League.of.Legends.Championship.Series': 'J:/Sportss/League of Legends Championship Series/2223',
'League.of.Legends.Master.Series': 'J:/Sportss/League of Legends Master Series/2223',
'German.Handball-Bundesliga': 'J:/Sportss/German Handball-Bundesliga/2223',
'Spanish.Liga.ASOBAL': 'J:/Sportss/Spanish Liga ASOBAL/2223',
'Hungarian.Nemzeti.Bajnokság.I': 'J:/Sportss/Hungarian Nemzeti Bajnokság I/2223',
'French.LNH.Division.1': 'J:/Sportss/French LNH Division 1/2223',
'Polish.Handball.Superliga': 'J:/Sportss/Polish Handball Superliga/2223',
'New.Zealand.Netball.League': 'J:/Sportss/New Zealand Netball League/2223',
'UK.Netball.Superleague': 'J:/Sportss/UK Netball Superleague/2223',
'Australian.Super.Netball.League': 'J:/Sportss/Australian Super Netball League/2223',
'_Defunct.Netball.Teams': 'J:/Sportss/_Defunct Netball Teams/2223',
'Greek.A1.Ethniki': 'J:/Sportss/Greek A1 Ethniki/2223',
'Turkish.Volleyball.League': 'J:/Sportss/Turkish Volleyball League/2223',
'Italian.Volleyball.League': 'J:/Sportss/Italian Volleyball League/2223',
'Russian.Volleyball.Super.League': 'J:/Sportss/Russian Volleyball Super League/2223',
'EuroLeague.Basketball': 'J:/Sportss/EuroLeague Basketball/2223',
'EuroCup.Basketball': 'J:/Sportss/EuroCup Basketball/2223',
'Basketball.Champions.League': 'J:/Sportss/Basketball Champions League/2223',
'FIBA.Basketball.World.Cup': 'J:/Sportss/FIBA Basketball World Cup/2223',
'European.Rugby.Champions.Cup': 'J:/Sportss/European Rugby Champions Cup/2223',
'Super.Rugby': 'J:/Sportss/Super Rugby/2223',
'AAF': 'J:/Sportss/AAF/Season 2023',
'LPGA.Tour': 'J:/Sportss/LPGA Tour/2223',
'PDC.Darts': 'J:/Sportss/PDC Darts/2223',
'World.Snooker': 'J:/Sportss/World Snooker/2223',
'Mens.FIH.Pro.League': 'J:/Sportss/Mens FIH Pro League/2223',
'Euro.Hockey.League': 'J:/Sportss/Euro Hockey League/2223',
'Hockey.World.Cup': 'J:/Sportss/Hockey World Cup/2223',
'BDO.Darts': 'J:/Sportss/BDO Darts/2223',
'International.Friendlies': 'J:/Sportss/International Friendlies/2223',
'AEW': 'J:/Sportss/AEW/Season 2023',
'International.Race.of.Champions': 'J:/Sportss/International Race of Champions/2223',
'FIFA.Womens.World.Cup': 'J:/Sportss/FIFA Womens World Cup/2223',
'UEFA.European.Under-21.Championship': 'J:/Sportss/UEFA European Under-21 Championship/2223',
'BKFC': 'J:/Sportss/BKFC/Season 2023',
'FIFA.eWorld.Cup.Series': 'J:/Sportss/FIFA eWorld Cup Series/2223',
'Club.Friendlies': 'J:/Sportss/Club Friendlies/2223',
'EFL.Cup': 'J:/Sportss/EFL Cup/2223',
'FA.Community.Shield': 'J:/Sportss/FA Community Shield/2223',
'NASCAR.Xfinity.Series': 'J:/Sportss/NASCAR Xfinity Series/2223',
'Rugby.World.Cup': 'J:/Sportss/Rugby World Cup/2223',
'Cricket.World.Cup': 'J:/Sportss/Cricket World Cup/2223',
'WTCR': 'J:/Sportss/WTCR/Season 2023',
'French.LNB.Pro.B': 'J:/Sportss/French LNB Pro B/2223',
'Polish.Basketball.League': 'J:/Sportss/Polish Basketball League/2223',
'Belgian.PBL': 'J:/Sportss/Belgian PBL/2223',
'Hungarian.Nemzeti.Bajnokság.IA': 'J:/Sportss/Hungarian Nemzeti Bajnokság IA/2223',
'Laver.Cup': 'J:/Sportss/Laver Cup/2223',
'French.Ligue.A.Mens.Volleyball': 'J:/Sportss/French Ligue A Mens Volleyball/2223',
'French.Ligue.A.Womens.Volleyball': 'J:/Sportss/French Ligue A Womens Volleyball/2223',
'Italian.Womens.Volleyball.League': 'J:/Sportss/Italian Womens Volleyball League/2223',
'Olympics.Field.Hockey': 'J:/Sportss/Olympics Field Hockey/2223',
'MXGP': 'J:/Sportss/MXGP/Season 2023',
'MotoE.World.Championship': 'J:/Sportss/MotoE World Championship/2223',
'English.RFL.Championship': 'J:/Sportss/English RFL Championship/2223',
'English.National.League': 'J:/Sportss/English National League/2223',
'Nippon.Baseball.League': 'J:/Sportss/Nippon Baseball League/2223',
'_Defunct.Baseball.Teams': 'J:/Sportss/_Defunct Baseball Teams/2223',
'AAA': 'J:/Sportss/AAA/Season 2023',
'AJPW': 'J:/Sportss/AJPW/Season 2023',
'CMLL': 'J:/Sportss/CMLL/Season 2023',
'NOAH': 'J:/Sportss/NOAH/Season 2023',
'UWF': 'J:/Sportss/UWF/Season 2023',
'UWF-i': 'J:/Sportss/UWF-i/Season 2023',
'RINGS': 'J:/Sportss/RINGS/Season 2023',
'Pancrase': 'J:/Sportss/Pancrase/Season 2023',
'DREAM': 'J:/Sportss/DREAM/Season 2023',
'DEEP': 'J:/Sportss/DEEP/Season 2023',
'IGF': 'J:/Sportss/IGF/Season 2023',
'Jungle.Fight': 'J:/Sportss/Jungle Fight/2223',
'K-1': 'J:/Sportss/K-1/Season 2023',
'NCAA.Division.I.Basketball.Mens': 'J:/Sportss/NCAA Division I Basketball Mens/2223',
'Battlarts': 'J:/Sportss/Battlarts/Season 2023',
'BJW': 'J:/Sportss/BJW/Season 2023',
'BML': 'J:/Sportss/BML/Season 2023',
'GCW': 'J:/Sportss/GCW/Season 2023',
'HUSTLE': 'J:/Sportss/HUSTLE/Season 2023',
'PWFG': 'J:/Sportss/PWFG/Season 2023',
'ZERO-1': 'J:/Sportss/ZERO-1/Season 2023',
'Argentinian.Primera.B.Nacional': 'J:/Sportss/Argentinian Primera B Nacional/2223',
'Albanian.Superliga': 'J:/Sportss/Albanian Superliga/2223',
'Andorran.1a.Divisió': 'J:/Sportss/Andorran 1a Divisió/2223',
'Armenian.Premier.League': 'J:/Sportss/Armenian Premier League/2223',
'Australia.ACT.NPL': 'J:/Sportss/Australia ACT NPL/2223',
'Austrian.Bundesliga': 'J:/Sportss/Austrian Bundesliga/2223',
'Belarus.Vyscha.Liga': 'J:/Sportss/Belarus Vyscha Liga/2223',
'Belgian.First.Division.B': 'J:/Sportss/Belgian First Division B/2223',
'Bosnian.Premier.Liga': 'J:/Sportss/Bosnian Premier Liga/2223',
'Brazilian.Serie.C': 'J:/Sportss/Brazilian Serie C/2223',
'Bulgarian.First.League': 'J:/Sportss/Bulgarian First League/2223',
'Chile.Primera.Division': 'J:/Sportss/Chile Primera Division/2223',
'China.League.One': 'J:/Sportss/China League One/2223',
'Croatian.First.Football.League': 'J:/Sportss/Croatian First Football League/2223',
'Cypriot.First.Division': 'J:/Sportss/Cypriot First Division/2223',
'Czech.First.League': 'J:/Sportss/Czech First League/2223',
'Danish.2nd.Division': 'J:/Sportss/Danish 2nd Division/2223',
'Japanese.J1.League': 'J:/Sportss/Japanese J1 League/2223',
'Estonian.Meistriliiga': 'J:/Sportss/Estonian Meistriliiga/2223',
'Faroe.Islands.Premier.League': 'J:/Sportss/Faroe Islands Premier League/2223',
'Finish.Veikkausliiga': 'J:/Sportss/Finish Veikkausliiga/2223',
'French.Championnat.National': 'J:/Sportss/French Championnat National/2223',
'Georgian.Erovnuli.Liga': 'J:/Sportss/Georgian Erovnuli Liga/2223',
'Germany.Liga.3': 'J:/Sportss/Germany Liga 3/2223',
'Greek.Super.League.2': 'J:/Sportss/Greek Super League 2/2223',
'Dutch.Eerste.Divisie': 'J:/Sportss/Dutch Eerste Divisie/2223',
'Icelandic.Úrvalsdeild.karla': 'J:/Sportss/Icelandic Úrvalsdeild karla/2223',
'Irish.Premier.Division': 'J:/Sportss/Irish Premier Division/2223',
'Israeli.Premier.League': 'J:/Sportss/Israeli Premier League/2223',
'Italy.Serie.D.Girone.D': 'J:/Sportss/Italy Serie D Girone D/2223',
'English.Northern.Premier.League.Premier.Division': 'J:/Sportss/English Northern Premier League Premier Division/2223',
'English.Isthmian.League.Premier.Division': 'J:/Sportss/English Isthmian League Premier Division/2223',
'English.Southern.Premier.League.South.Division': 'J:/Sportss/English Southern Premier League South Division/2223',
'Kazakhstan.Premier.League': 'J:/Sportss/Kazakhstan Premier League/2223',
'Latvian.Higher.League': 'J:/Sportss/Latvian Higher League/2223',
'Lithuanian.A.Lyga': 'J:/Sportss/Lithuanian A Lyga/2223',
'Macedonian.First.League': 'J:/Sportss/Macedonian First League/2223',
'Maltese.Premier.League': 'J:/Sportss/Maltese Premier League/2223',
'Mexican.Ascenso.MX': 'J:/Sportss/Mexican Ascenso MX/2223',
'Moldovan.National.Division': 'J:/Sportss/Moldovan National Division/2223',
'Montenegrin.First.League': 'J:/Sportss/Montenegrin First League/2223',
'Moroccan.Botola.2': 'J:/Sportss/Moroccan Botola 2/2223',
'Northern.Irish.Premiership': 'J:/Sportss/Northern Irish Premiership/2223',
'Polish.I.liga': 'J:/Sportss/Polish I liga/2223',
'Portuguese.LigaPro': 'J:/Sportss/Portuguese LigaPro/2223',
'Qatar.Stars.League': 'J:/Sportss/Qatar Stars League/2223',
'Romanian.Liga.II': 'J:/Sportss/Romanian Liga II/2223',
'Russian.Football.National.League': 'J:/Sportss/Russian Football National League/2223',
'San-Marino.Campionato': 'J:/Sportss/San-Marino Campionato/2223',
'Saudi-Arabian.Pro.League': 'J:/Sportss/Saudi-Arabian Pro League/2223',
'Scottish.League.1': 'J:/Sportss/Scottish League 1/2223',
'Scottish.League.2': 'J:/Sportss/Scottish League 2/2223',
'Serbian.Super.Liga': 'J:/Sportss/Serbian Super Liga/2223',
'Slovakian.Super.Liga': 'J:/Sportss/Slovakian Super Liga/2223',
'Primera.División.RFEF.Group.1': 'J:/Sportss/Primera División RFEF Group 1/2223',
'Swedish.Division.1.North': 'J:/Sportss/Swedish Division 1 North/2223',
'Swiss.Super.League': 'J:/Sportss/Swiss Super League/2223',
'Turkish.1.Lig': 'J:/Sportss/Turkish 1 Lig/2223',
'Ukrainian.First.League': 'J:/Sportss/Ukrainian First League/2223',
'UAE.Pro.League': 'J:/Sportss/UAE Pro League/2223',
'Turkish.2.Lig': 'J:/Sportss/Turkish 2 Lig/2223',
'English.National.League.North': 'J:/Sportss/English National League North/2223',
'English.National.League.South': 'J:/Sportss/English National League South/2223',
'Danish.1st.Division': 'J:/Sportss/Danish 1st Division/2223',
'American.USL.Championship': 'J:/Sportss/American USL Championship/2223',
'Bolivian.Primera.División': 'J:/Sportss/Bolivian Primera División/2223',
'Ecuadorian.Serie.A': 'J:/Sportss/Ecuadorian Serie A/2223',
'Paraguayan.Primera.Division': 'J:/Sportss/Paraguayan Primera Division/2223',
'Peruvian.Primera.Division': 'J:/Sportss/Peruvian Primera Division/2223',
'South.Korean.K.League.1': 'J:/Sportss/South Korean K League 1/2223',
'Hungarian.NB.I': 'J:/Sportss/Hungarian NB I/2223',
'Romanian.Liga.I': 'J:/Sportss/Romanian Liga I/2223',
'Slovenian.1..SNL': 'J:/Sportss/Slovenian 1  SNL/2223',
'Azerbaijani.Premier.League': 'J:/Sportss/Azerbaijani Premier League/2223',
'Luxembourg.National.Division': 'J:/Sportss/Luxembourg National Division/2223',
'German.Regionalliga.Nord': 'J:/Sportss/German Regionalliga Nord/2223',
'Pride.FC': 'J:/Sportss/Pride FC/2223',
'FREEDOMS': 'J:/Sportss/FREEDOMS/Season 2023',
'UFO': 'J:/Sportss/UFO/Season 2023',
'VTJ': 'J:/Sportss/VTJ/Season 2023',
'World.Japan': 'J:/Sportss/World Japan/2223',
'U-STYLE': 'J:/Sportss/U-STYLE/Season 2023',
'WAR': 'J:/Sportss/WAR/Season 2023',
'Michinoku.Pro': 'J:/Sportss/Michinoku Pro/2223',
'KINGDOM': 'J:/Sportss/KINGDOM/Season 2023',
'AJW': 'J:/Sportss/AJW/Season 2023',
'W-1': 'J:/Sportss/W-1/Season 2023',
'Zona.23': 'J:/Sportss/Zona 23/2223',
'KSW': 'J:/Sportss/KSW/Season 2023',
'WLC': 'J:/Sportss/WLC/Season 2023',
'Sumo': 'J:/Sportss/Sumo/Season 2023',
'Extreme.E': 'J:/Sportss/Extreme E/2223',
'Swiss.Challenge.League': 'J:/Sportss/Swiss Challenge League/2223',
'Six.Nations.Championship': 'J:/Sportss/Six Nations Championship/2223',
'Call.of.Duty.League': 'J:/Sportss/Call of Duty League/2223',
'Call.of.Duty.World.League': 'J:/Sportss/Call of Duty World League/2223',
'Overwatch.League': 'J:/Sportss/Overwatch League/2223',
'XFL': 'J:/Sportss/XFL/Season 2023',
'AFC.Champions.League': 'J:/Sportss/AFC Champions League/2223',
'CAF.Champions.League': 'J:/Sportss/CAF Champions League/2223',
'CONCACAF.Champions.League': 'J:/Sportss/CONCACAF Champions League/2223',
'English.RFU.Championship': 'J:/Sportss/English RFU Championship/2223',
'Scottish.FA.Cup': 'J:/Sportss/Scottish FA Cup/2223',
'Copa.Sudamericana': 'J:/Sportss/Copa Sudamericana/2223',
'Copa.do.Brasil': 'J:/Sportss/Copa do Brasil/2223',
'Professional.Wrestling': 'J:/Sportss/Professional Wrestling/2223',
'Mixed.Martial.Arts': 'J:/Sportss/Mixed Martial Arts/2223',
'Diamond.Ring': 'J:/Sportss/Diamond Ring/2223',
'SRC': 'J:/Sportss/SRC/Season 2023',
'World.Rallycross.Championship': 'J:/Sportss/World Rallycross Championship/2223',
'Isle.of.Man.TT': 'J:/Sportss/Isle of Man TT/2223',
'Argentine.LNB': 'J:/Sportss/Argentine LNB/2223',
'Shoot.Boxing': 'J:/Sportss/Shoot Boxing/2223',
'Shooto': 'J:/Sportss/Shooto/Season 2023',
'RISE': 'J:/Sportss/RISE/Season 2023',
'American.AHL': 'J:/Sportss/American AHL/2223',
'CONCACAF.League': 'J:/Sportss/CONCACAF League/2223',
'South.African.Sunshine.Tour': 'J:/Sportss/South African Sunshine Tour/2223',
'Iranian.Azadegan.League': 'J:/Sportss/Iranian Azadegan League/2223',
'Iranian.Persian.Gulf.Pro.League': 'J:/Sportss/Iranian Persian Gulf Pro League/2223',
'Thai.Premier.League': 'J:/Sportss/Thai Premier League/2223',
'Thai.League.2': 'J:/Sportss/Thai League 2/2223',
'Kenyan.Premier.League': 'J:/Sportss/Kenyan Premier League/2223',
'German.Regionalliga.West': 'J:/Sportss/German Regionalliga West/2223',
'German.Regionalliga.SudWest': 'J:/Sportss/German Regionalliga SudWest/2223',
'German.Regionalliga.Bayern': 'J:/Sportss/German Regionalliga Bayern/2223',
'German.Regionalliga.Nordost': 'J:/Sportss/German Regionalliga Nordost/2223',
'Primera.División.RFEF.Group.2': 'J:/Sportss/Primera División RFEF Group 2/2223',
'Spanish.Segunda.División.B.Group.3': 'J:/Sportss/Spanish Segunda División B Group 3/2223',
'Spanish.Segunda.División.B.Group.4': 'J:/Sportss/Spanish Segunda División B Group 4/2223',
'Algerian.Ligue.1': 'J:/Sportss/Algerian Ligue 1/2223',
'Senegal.Ligue.1': 'J:/Sportss/Senegal Ligue 1/2223',
'Northern.Irish.Championship': 'J:/Sportss/Northern Irish Championship/2223',
'Svenska.Cupen': 'J:/Sportss/Svenska Cupen/2223',
'Irish.First.Division': 'J:/Sportss/Irish First Division/2223',
'European.Challenge.Tour': 'J:/Sportss/European Challenge Tour/2223',
'China.Tour': 'J:/Sportss/China Tour/2223',
'Japan.Golf.Tour': 'J:/Sportss/Japan Golf Tour/2223',
'PGA.Tour.of.Australasia': 'J:/Sportss/PGA Tour of Australasia/2223',
'Asian.Tour': 'J:/Sportss/Asian Tour/2223',
'Korn.Ferry.Tour': 'J:/Sportss/Korn Ferry Tour/2223',
'PGA.Tour.Latinoamérica': 'J:/Sportss/PGA Tour Latinoamérica/2223',
'PGA.Tour.Canada': 'J:/Sportss/PGA Tour Canada/2223',
'Korean.Tour': 'J:/Sportss/Korean Tour/2223',
'Asian.Development.Tour': 'J:/Sportss/Asian Development Tour/2223',
'Alps.Tour': 'J:/Sportss/Alps Tour/2223',
'Nordic.Golf.League': 'J:/Sportss/Nordic Golf League/2223',
'PGA.EuroPro.Tour': 'J:/Sportss/PGA EuroPro Tour/2223',
'ProGolf.Tour': 'J:/Sportss/ProGolf Tour/2223',
'MENA.Golf.Tour': 'J:/Sportss/MENA Golf Tour/2223',
'Big.Easy.Tour': 'J:/Sportss/Big Easy Tour/2223',
'PGA.Tour.China': 'J:/Sportss/PGA Tour China/2223',
'All.Thailand.Golf.Tour': 'J:/Sportss/All Thailand Golf Tour/2223',
'Professional.Golf.Tour.of.India': 'J:/Sportss/Professional Golf Tour of India/2223',
'Japan.Challenge.Tour': 'J:/Sportss/Japan Challenge Tour/2223',
'Italy.Serie.D.Girone.B': 'J:/Sportss/Italy Serie D Girone B/2223',
'Italy.Serie.D.Girone.C': 'J:/Sportss/Italy Serie D Girone C/2223',
'Italy.Serie.D.Girone.E': 'J:/Sportss/Italy Serie D Girone E/2223',
'Italy.Serie.D.Girone.F': 'J:/Sportss/Italy Serie D Girone F/2223',
'Italy.Serie.D.Girone.G': 'J:/Sportss/Italy Serie D Girone G/2223',
'Italy.Serie.D.Girone.H': 'J:/Sportss/Italy Serie D Girone H/2223',
'Italy.Serie.D.Girone.I': 'J:/Sportss/Italy Serie D Girone I/2223',
'Italy.Serie.D.Girone.A': 'J:/Sportss/Italy Serie D Girone A/2223',
'Kickboxing': 'J:/Sportss/Kickboxing/Season 2023',
'FA.Trophy': 'J:/Sportss/FA Trophy/2223',
'Malaysian.Premier.League': 'J:/Sportss/Malaysian Premier League/2223',
'Indonesian.Super.League': 'J:/Sportss/Indonesian Super League/2223',
'Indian.Super.League': 'J:/Sportss/Indian Super League/2223',
'Malaysian.Super.League': 'J:/Sportss/Malaysian Super League/2223',
'Cambodia.C-League': 'J:/Sportss/Cambodia C-League/2223',
'Uzbekistan.Super.League': 'J:/Sportss/Uzbekistan Super League/2223',
'Singapore.Premier.League': 'J:/Sportss/Singapore Premier League/2223',
'Austrian.Erste.Liga': 'J:/Sportss/Austrian Erste Liga/2223',
'Indian.I-League': 'J:/Sportss/Indian I-League/2223',
'Glory': 'J:/Sportss/Glory/Season 2023',
'Affliction': 'J:/Sportss/Affliction/Season 2023',
'Strikeforce': 'J:/Sportss/Strikeforce/Season 2023',
'One.Day.International.Series': 'J:/Sportss/One Day International Series/2223',
'South.African.Premier.Soccer.League': 'J:/Sportss/South African Premier Soccer League/2223',
'Vietnamese.V.League.1': 'J:/Sportss/Vietnamese V League 1/2223',
'AFC.Cup': 'J:/Sportss/AFC Cup/2223',
'Australian.A-League.Women': 'J:/Sportss/Australian A-League Women/2223',
'Nicaragua.Primera.Division': 'J:/Sportss/Nicaragua Primera Division/2223',
'Heros': 'J:/Sportss/Heros/Season 2023',
'_Defunct.Cricket.Teams': 'J:/Sportss/_Defunct Cricket Teams/2223',
'_Defunct.American.Football.Teams': 'J:/Sportss/_Defunct American Football Teams/2223',
'_Defunct.Ice.Hockey.Teams': 'J:/Sportss/_Defunct Ice Hockey Teams/2223',
'Tajikistan.Vysshaya.Liga': 'J:/Sportss/Tajikistan Vysshaya Liga/2223',
'Belarusian.First.League': 'J:/Sportss/Belarusian First League/2223',
'Belarus.Coppa': 'J:/Sportss/Belarus Coppa/2223',
'New-Zealand.Football.Championship': 'J:/Sportss/New-Zealand Football Championship/2223',
'Costa-Rica.Liga.FPD': 'J:/Sportss/Costa-Rica Liga FPD/2223',
'El.Salvador.Primera.Division': 'J:/Sportss/El Salvador Primera Division/2223',
'Guatemala.Liga.Nacional': 'J:/Sportss/Guatemala Liga Nacional/2223',
'Honduras.Liga.Nacional.de.Futbol': 'J:/Sportss/Honduras Liga Nacional de Futbol/2223',
'Panama.Liga.Panamena.de.Futbol': 'J:/Sportss/Panama Liga Panamena de Futbol/2223',
'Canadian.Premier.League': 'J:/Sportss/Canadian Premier League/2223',
'Indian.I-League.2nd.Division': 'J:/Sportss/Indian I-League 2nd Division/2223',
'South.Korean.K.League.2': 'J:/Sportss/South Korean K League 2/2223',
'Kuwait.Premier.League': 'J:/Sportss/Kuwait Premier League/2223',
'Japanese.J2.League': 'J:/Sportss/Japanese J2 League/2223',
'Hong-Kong.Premier.League': 'J:/Sportss/Hong-Kong Premier League/2223',
'Bahrain.Premier.League': 'J:/Sportss/Bahrain Premier League/2223',
'Nigerian.NPFL': 'J:/Sportss/Nigerian NPFL/2223',
'Tunisian.Ligue.1': 'J:/Sportss/Tunisian Ligue 1/2223',
'Egyptian.Premier.League': 'J:/Sportss/Egyptian Premier League/2223',
'Korean.KBO.League': 'J:/Sportss/Korean KBO League/2223',
'FIBA.EuroBasket': 'J:/Sportss/FIBA EuroBasket/2223',
'Spanish.Copa.del.Rey.de.Baloncesto': 'J:/Sportss/Spanish Copa del Rey de Baloncesto/2223',
'Spanish.Supercup.of.Basketball': 'J:/Sportss/Spanish Supercup of Basketball/2223',
'_No.League.Soccer': 'J:/Sportss/_No League Soccer/2223',
'_No.League.Motorsports': 'J:/Sportss/_No League Motorsports/2223',
'_No.League.Basketball': 'J:/Sportss/_No League Basketball/2223',
'_No.League.Baseball': 'J:/Sportss/_No League Baseball/2223',
'_No.League.Ice.Hockey': 'J:/Sportss/_No League Ice Hockey/2223',
'_No.League.American.Football': 'J:/Sportss/_No League American Football/2223',
'_No.League.Fighting': 'J:/Sportss/_No League Fighting/2223',
'_No.League.Cricket': 'J:/Sportss/_No League Cricket/2223',
'_No.League.Netball': 'J:/Sportss/_No League Netball/2223',
'ILFJ': 'J:/Sportss/ILFJ/Season 2023',
'International.Test.Match.Series': 'J:/Sportss/International Test Match Series/2223',
'Swedish.Division.1.South': 'J:/Sportss/Swedish Division 1 South/2223',
'GLEAT': 'J:/Sportss/GLEAT/Season 2023',
'EFL.Trophy': 'J:/Sportss/EFL Trophy/2223',
'Jaguar.I-Pace.eTrophy': 'J:/Sportss/Jaguar I-Pace eTrophy/2223',
'English.Womens.Super.League': 'J:/Sportss/English Womens Super League/2223',
'FIBA.AmeriCup': 'J:/Sportss/FIBA AmeriCup/2223',
'_Defunct.Cycling.Teams': 'J:/Sportss/_Defunct Cycling Teams/2223',
'ADCC': 'J:/Sportss/ADCC/Season 2023',
'Quintet.': 'J:/Sportss/Quintet/2223',
'RJPW': 'J:/Sportss/RJPW/Season 2023',
'KOPW': 'J:/Sportss/KOPW/Season 2023',
'Riki.Pro': 'J:/Sportss/Riki Pro/2223',
'Dradition': 'J:/Sportss/Dradition/Season 2023',
'SWS': 'J:/Sportss/SWS/Season 2023',
'IFL': 'J:/Sportss/IFL/Season 2023',
'ZST': 'J:/Sportss/ZST/Season 2023',
'Its.Showtime': 'J:/Sportss/Its Showtime/2223',
'KO': 'J:/Sportss/KO/Season 2023',
'PGA.Tour.Champions': 'J:/Sportss/PGA Tour Champions/2223',
'UEFA.Womens.Euro': 'J:/Sportss/UEFA Womens Euro/2223',
'AFC.Asian.Cup': 'J:/Sportss/AFC Asian Cup/2223',
'OFC.Nations.Cup': 'J:/Sportss/OFC Nations Cup/2223',
'IMSA.Prototype.Challenge.Series': 'J:/Sportss/IMSA Prototype Challenge Series/2223',
'IMSA.Pilot.Challenge': 'J:/Sportss/IMSA Pilot Challenge/2223',
'Porsche.GT3.Cup.Challenge': 'J:/Sportss/Porsche GT3 Cup Challenge/2223',
'Lamborghini.Super.Trofeo.North.America': 'J:/Sportss/Lamborghini Super Trofeo North America/2223',
'Ferrari.Challenge.North.America': 'J:/Sportss/Ferrari Challenge North America/2223',
'CONCACAF.Gold.Cup': 'J:/Sportss/CONCACAF Gold Cup/2223',
'eNASCAR.iRacing.Series': 'J:/Sportss/eNASCAR iRacing Series/2223',
'Top.Rank': 'J:/Sportss/Top Rank/2223',
'AJKF': 'J:/Sportss/AJKF/Season 2023',
'KJP': 'J:/Sportss/KJP/Season 2023',
'TPW': 'J:/Sportss/TPW/Season 2023',
'USWF': 'J:/Sportss/USWF/Season 2023',
'KOTC': 'J:/Sportss/KOTC/Season 2023',
'EliteXC': 'J:/Sportss/EliteXC/Season 2023',
'NCAA.Fighting': 'J:/Sportss/NCAA Fighting/2223',
'World.Extreme.Cagefighting': 'J:/Sportss/World Extreme Cagefighting/2223',
'Spanish.Segunda.División.B.Group.5': 'J:/Sportss/Spanish Segunda División B Group 5/2223',
'FA.Womens.League.Cup': 'J:/Sportss/FA Womens League Cup/2223',
'Scottish.League.Cup': 'J:/Sportss/Scottish League Cup/2223',
'UEFA.Womens.Champions.League': 'J:/Sportss/UEFA Womens Champions League/2223',
'EuroBasket.Women': 'J:/Sportss/EuroBasket Women/2223',
'FIBA.Womens.World.Cup': 'J:/Sportss/FIBA Womens World Cup/2223',
'EuroLeague.Women': 'J:/Sportss/EuroLeague Women/2223',
'European.Womens.Handball.Championship': 'J:/Sportss/European Womens Handball Championship/2223',
'European.Mens.Handball.Championship': 'J:/Sportss/European Mens Handball Championship/2223',
'World.Mens.Handball.Championship': 'J:/Sportss/World Mens Handball Championship/2223',
'World.Womens.Handball.Championship': 'J:/Sportss/World Womens Handball Championship/2223',
'FIBA.AfroBasket': 'J:/Sportss/FIBA AfroBasket/2223',
'FIBA.Asia.Cup': 'J:/Sportss/FIBA Asia Cup/2223',
'Chile.Primera.B': 'J:/Sportss/Chile Primera B/2223',
'Paraguayan.División.Intermedia': 'J:/Sportss/Paraguayan División Intermedia/2223',
'French.Trophée.des.Champions': 'J:/Sportss/French Trophée des Champions/2223',
'Dutch.KNVB.Cup': 'J:/Sportss/Dutch KNVB Cup/2223',
'German.Super.Cup': 'J:/Sportss/German Super Cup/2223',
'Andorran.Segona.Divisió': 'J:/Sportss/Andorran Segona Divisió/2223',
'Andorran.Cup': 'J:/Sportss/Andorran Cup/2223',
'Icelandic.1.deild.karla': 'J:/Sportss/Icelandic 1 deild karla/2223',
'Albanian.Kategoria.e.Parë': 'J:/Sportss/Albanian Kategoria e Parë/2223',
'Armenian.First.League': 'J:/Sportss/Armenian First League/2223',
'Armenian.Cup': 'J:/Sportss/Armenian Cup/2223',
'Bolivian.Nacional.B.Copa.Simón.Bolívar': 'J:/Sportss/Bolivian Nacional B Copa Simón Bolívar/2223',
'Bosnian.First.League': 'J:/Sportss/Bosnian First League/2223',
'Bosnian.First.League.of.Srpska': 'J:/Sportss/Bosnian First League of Srpska/2223',
'Bulgarian.Second.League': 'J:/Sportss/Bulgarian Second League/2223',
'Azerbaijan.First.Division': 'J:/Sportss/Azerbaijan First Division/2223',
'Azerbaijan.Cup': 'J:/Sportss/Azerbaijan Cup/2223',
'American.ECHL': 'J:/Sportss/American ECHL/2223',
'American.USHL': 'J:/Sportss/American USHL/2223',
'American.FPHL': 'J:/Sportss/American FPHL/2223',
'Russian.VHL': 'J:/Sportss/Russian VHL/2223',
'Russian.KHL': 'J:/Sportss/Russian KHL/2223',
'Latvian.Optibet.Hockey.League': 'J:/Sportss/Latvian Optibet Hockey League/2223',
'Ukrainian.UHL': 'J:/Sportss/Ukrainian UHL/2223',
'Czech.Extraliga': 'J:/Sportss/Czech Extraliga/2223',
'Belarusian.Extraleague': 'J:/Sportss/Belarusian Extraleague/2223',
'German.DEL': 'J:/Sportss/German DEL/2223',
'Norwegian.Fjordkraft-ligaen': 'J:/Sportss/Norwegian Fjordkraft-ligaen/2223',
'French.Ligue.Magnus': 'J:/Sportss/French Ligue Magnus/2223',
'Polish.Hockey.League': 'J:/Sportss/Polish Hockey League/2223',
'Slovak.Hockey.League': 'J:/Sportss/Slovak Hockey League/2223',
'Danish.Metal.Ligaen': 'J:/Sportss/Danish Metal Ligaen/2223',
'Finnish.Liiga': 'J:/Sportss/Finnish Liiga/2223',
'Slovak.Extraliga': 'J:/Sportss/Slovak Extraliga/2223',
'Austrian.ICE.Hockey.League': 'J:/Sportss/Austrian ICE Hockey League/2223',
'Swiss.National.League': 'J:/Sportss/Swiss National League/2223',
'Finnish.Mestis': 'J:/Sportss/Finnish Mestis/2223',
'German.DEL.2': 'J:/Sportss/German DEL 2/2223',
'IVC': 'J:/Sportss/IVC/Season 2023',
'Meca': 'J:/Sportss/Meca/Season 2023',
'Colombian.Categoría.Primera.B': 'J:/Sportss/Colombian Categoría Primera B/2223',
'Croatian.Druga.HNL': 'J:/Sportss/Croatian Druga HNL/2223',
'Cypriot.Second.Division': 'J:/Sportss/Cypriot Second Division/2223',
'Czech.National.Football.League': 'J:/Sportss/Czech National Football League/2223',
'DR.Congo.Ligue.1': 'J:/Sportss/DR Congo Ligue 1/2223',
'Dominican.LDF': 'J:/Sportss/Dominican LDF/2223',
'Ecuadorian.Serie.B': 'J:/Sportss/Ecuadorian Serie B/2223',
'Estonian.Esiliiga': 'J:/Sportss/Estonian Esiliiga/2223',
'Ethiopian.Premier.League': 'J:/Sportss/Ethiopian Premier League/2223',
'Turkish.Cup': 'J:/Sportss/Turkish Cup/2223',
'Faroe.Islands.1..deild': 'J:/Sportss/Faroe Islands 1  deild/2223',
'Fijian.Premier.League': 'J:/Sportss/Fijian Premier League/2223',
'Finnish.Ykkönen': 'J:/Sportss/Finnish Ykkönen/2223',
'Gibraltarian.National.League': 'J:/Sportss/Gibraltarian National League/2223',
'Hungarian.NB.II': 'J:/Sportss/Hungarian NB II/2223',
'Israeli.Liga.Leumit': 'J:/Sportss/Israeli Liga Leumit/2223',
'Japanese.J3.League': 'J:/Sportss/Japanese J3 League/2223',
'Kosovan.Superleague': 'J:/Sportss/Kosovan Superleague/2223',
'Kyrgyz.Premier.League': 'J:/Sportss/Kyrgyz Premier League/2223',
'Lao.Premier.League': 'J:/Sportss/Lao Premier League/2223',
'Emir.of.Qatar.Cup': 'J:/Sportss/Emir of Qatar Cup/2223',
'Liechtenstein.Cup': 'J:/Sportss/Liechtenstein Cup/2223',
'Georgian.Erovnuli.Liga.2': 'J:/Sportss/Georgian Erovnuli Liga 2/2223',
'Ghanaian.Premier.League': 'J:/Sportss/Ghanaian Premier League/2223',
'Olympic.Games': 'J:/Sportss/Olympic Games/2223',
'Mens.Ice.Hockey.World.Championships': 'J:/Sportss/Mens Ice Hockey World Championships/2223',
'Japanese.B1.League': 'J:/Sportss/Japanese B1 League/2223',
'AAW.Pro': 'J:/Sportss/AAW Pro/2223',
'Twenty20.International.Series': 'J:/Sportss/Twenty20 International Series/2223',
'EHF.Champions.League': 'J:/Sportss/EHF Champions League/2223',
'North.American.Rugby.League': 'J:/Sportss/North American Rugby League/2223',
'FIBA.Womens.AmeriCup': 'J:/Sportss/FIBA Womens AmeriCup/2223',
'Rugby.Europe.Championship': 'J:/Sportss/Rugby Europe Championship/2223',
'Autumn.Nations.Cup': 'J:/Sportss/Autumn Nations Cup/2223',
'Pacific.Nations.Cup': 'J:/Sportss/Pacific Nations Cup/2223',
'Rugby.Championship': 'J:/Sportss/Rugby Championship/2223',
'AIW.Wrestling': 'J:/Sportss/AIW Wrestling/2223',
'CHIKARA.Pro': 'J:/Sportss/CHIKARA Pro/2223',
'Combat.Zone.Wrestling': 'J:/Sportss/Combat Zone Wrestling/2223',
'EVOLVE.Wrestling': 'J:/Sportss/EVOLVE Wrestling/2223',
'MLW': 'J:/Sportss/MLW/Season 2023',
'PROGRESS.Wrestling': 'J:/Sportss/PROGRESS Wrestling/2223',
'Pro.Wrestling.Guerrilla': 'J:/Sportss/Pro Wrestling Guerrilla/2223',
'Olympics.Athletics': 'J:/Sportss/Olympics Athletics/2223',
'Olympics.Badminton': 'J:/Sportss/Olympics Badminton/2223',
'Olympics.Climbing': 'J:/Sportss/Olympics Climbing/2223',
'Olympics.Equestrian': 'J:/Sportss/Olympics Equestrian/2223',
'Olympics.Fencing': 'J:/Sportss/Olympics Fencing/2223',
'Olympics.Shooting': 'J:/Sportss/Olympics Shooting/2223',
'Olympics.Table.Tennis': 'J:/Sportss/Olympics Table Tennis/2223',
'Olympics.Modern.Pentathlon': 'J:/Sportss/Olympics Modern Pentathlon/2223',
'Olympics.Weightlifting': 'J:/Sportss/Olympics Weightlifting/2223',
'World.Athletics.Championships': 'J:/Sportss/World Athletics Championships/2223',
'Commonwealth.Games.Athletics': 'J:/Sportss/Commonwealth Games Athletics/2223',
'Olympics.Skateboarding': 'J:/Sportss/Olympics Skateboarding/2223',
'Australia.Northern.NSW.NPL': 'J:/Sportss/Australia Northern NSW NPL/2223',
'Australia.New.South.Wales.NPL': 'J:/Sportss/Australia New South Wales NPL/2223',
'Australia.Victoria.NPL': 'J:/Sportss/Australia Victoria NPL/2223',
'Australia.Brisbane.Premier.League': 'J:/Sportss/Australia Brisbane Premier League/2223',
'Australia.Queensland.NPL': 'J:/Sportss/Australia Queensland NPL/2223',
'Australia.Western.Australia.NPL': 'J:/Sportss/Australia Western Australia NPL/2223',
'Australia.South.Australia.NPL': 'J:/Sportss/Australia South Australia NPL/2223',
'Australia.Northern.Territory.Premier.League': 'J:/Sportss/Australia Northern Territory Premier League/2223',
'Olympics.Baseball': 'J:/Sportss/Olympics Baseball/2223',
'Olympics.SoftBall': 'J:/Sportss/Olympics SoftBall/2223',
'Olympics.Basketball': 'J:/Sportss/Olympics Basketball/2223',
'Olympics.3x3.Basketball': 'J:/Sportss/Olympics 3x3 Basketball/2223',
'Olympics.Mountain.Bike': 'J:/Sportss/Olympics Mountain Bike/2223',
'Olympics.BMX.Freestyle': 'J:/Sportss/Olympics BMX Freestyle/2223',
'Olympics.BMX.Racing': 'J:/Sportss/Olympics BMX Racing/2223',
'Olympics.Road.Cycling': 'J:/Sportss/Olympics Road Cycling/2223',
'Olympics.Track.Cycling': 'J:/Sportss/Olympics Track Cycling/2223',
'Olympics.Boxing': 'J:/Sportss/Olympics Boxing/2223',
'Olympics.Judo': 'J:/Sportss/Olympics Judo/2223',
'Olympics.Karate': 'J:/Sportss/Olympics Karate/2223',
'Olympics.Taekwondo': 'J:/Sportss/Olympics Taekwondo/2223',
'Olympics.Wrestling': 'J:/Sportss/Olympics Wrestling/2223',
'Olympics.Golf': 'J:/Sportss/Olympics Golf/2223',
'Olympics.Artistic.Gymnastics': 'J:/Sportss/Olympics Artistic Gymnastics/2223',
'Olympics.Rhythmic.Gymnastics': 'J:/Sportss/Olympics Rhythmic Gymnastics/2223',
'Olympics.Handball': 'J:/Sportss/Olympics Handball/2223',
'Olympics.Triathlon': 'J:/Sportss/Olympics Triathlon/2223',
'Olympics.7s.Rugby': 'J:/Sportss/Olympics 7s Rugby/2223',
'Olympics.Archery': 'J:/Sportss/Olympics Archery/2223',
'Olympics.Soccer': 'J:/Sportss/Olympics Soccer/2223',
'Olympics.Tennis': 'J:/Sportss/Olympics Tennis/2223',
'Olympics.Beach.Volleyball': 'J:/Sportss/Olympics Beach Volleyball/2223',
'Olympics.Volleyball': 'J:/Sportss/Olympics Volleyball/2223',
'Olympics.Artistic.Swimming': 'J:/Sportss/Olympics Artistic Swimming/2223',
'Olympics.Canoe.Slalom': 'J:/Sportss/Olympics Canoe Slalom/2223',
'Olympics.Canoe.Sprint': 'J:/Sportss/Olympics Canoe Sprint/2223',
'Olympics.Diving': 'J:/Sportss/Olympics Diving/2223',
'Olympics.Marathon.Swimming': 'J:/Sportss/Olympics Marathon Swimming/2223',
'Olympics.Rowing': 'J:/Sportss/Olympics Rowing/2223',
'Olympics.Sailing': 'J:/Sportss/Olympics Sailing/2223',
'Olympics.Surfing': 'J:/Sportss/Olympics Surfing/2223',
'Olympics.Swimming': 'J:/Sportss/Olympics Swimming/2223',
'Olympics.Trampoline': 'J:/Sportss/Olympics Trampoline/2223',
'Olympics.Water.Polo': 'J:/Sportss/Olympics Water Polo/2223',
'Australia.Tasmania.NPL': 'J:/Sportss/Australia Tasmania NPL/2223',
'Jordanian.Pro.League': 'J:/Sportss/Jordanian Pro League/2223',
'Iraqi.Premier.League': 'J:/Sportss/Iraqi Premier League/2223',
'CAF.Confederation.Cup': 'J:/Sportss/CAF Confederation Cup/2223',
'House.of.Hardcore': 'J:/Sportss/House of Hardcore/2223',
'Riptide.Wrestling': 'J:/Sportss/Riptide Wrestling/2223',
'Bar.Wrestling': 'J:/Sportss/Bar Wrestling/2223',
'Frontier.Martial-Arts.Wrestling': 'J:/Sportss/Frontier Martial-Arts Wrestling/2223',
'European.League.of.Football': 'J:/Sportss/European League of Football/2223',
'Liga.Mexicana.de.Béisbol': 'J:/Sportss/Liga Mexicana de Béisbol/2223',
'Pacific.Coast.League': 'J:/Sportss/Pacific Coast League/2223',
'New.Zealand.NBL': 'J:/Sportss/New Zealand NBL/2223',
'Pakistan.Super.League': 'J:/Sportss/Pakistan Super League/2223',
'New.Zealand.Ice.Hockey.League': 'J:/Sportss/New Zealand Ice Hockey League/2223',
'Currie.Cup': 'J:/Sportss/Currie Cup/2223',
'Major.League.Rugby': 'J:/Sportss/Major League Rugby/2223',
'UEFA.Europa.Conference.League': 'J:/Sportss/UEFA Europa Conference League/2223',
'Uruguayan.Segunda.División': 'J:/Sportss/Uruguayan Segunda División/2223',
'Peruvian.Segunda.División': 'J:/Sportss/Peruvian Segunda División/2223',
'Serbian.Prva.Liga': 'J:/Sportss/Serbian Prva Liga/2223',
'Jamaican.Premier.League': 'J:/Sportss/Jamaican Premier League/2223',
'USL.League.One': 'J:/Sportss/USL League One/2223',
'USL.League.Two': 'J:/Sportss/USL League Two/2223',
'Bangladesh.Premier.League': 'J:/Sportss/Bangladesh Premier League/2223',
'Brazil.Serie.D': 'J:/Sportss/Brazil Serie D/2223',
'Taiwan.Mulan.Football.League': 'J:/Sportss/Taiwan Mulan Football League/2223',
'Lucha.Underground': 'J:/Sportss/Lucha Underground/2223',
'Six.Nations.Under.20s.Championship': 'J:/Sportss/Six Nations Under 20s Championship/2223',
'FIVB.Volleyball.Mens.Nations.League': 'J:/Sportss/FIVB Volleyball Mens Nations League/2223',
'FIVB.Volleyball.Womens.Nations.League': 'J:/Sportss/FIVB Volleyball Womens Nations League/2223',
'International.League': 'J:/Sportss/International League/2223',
'Spanish.Primera.RFEF.Group.1': 'J:/Sportss/Spanish Primera RFEF Group 1/2223',
'Spanish.Segunda.RFEF.Group.1': 'J:/Sportss/Spanish Segunda RFEF Group 1/2223',
'Spanish.Primera.RFEF.Group.2': 'J:/Sportss/Spanish Primera RFEF Group 2/2223',
'Spanish.Segunda.RFEF.Group.2': 'J:/Sportss/Spanish Segunda RFEF Group 2/2223',
'Spanish.Segunda.RFEF.Group.3': 'J:/Sportss/Spanish Segunda RFEF Group 3/2223',
'Spanish.Segunda.RFEF.Group.4': 'J:/Sportss/Spanish Segunda RFEF Group 4/2223',
'Spanish.Segunda.RFEF.Group.5': 'J:/Sportss/Spanish Segunda RFEF Group 5/2223',
'NASCAR.Truck.Series': 'J:/Sportss/NASCAR Truck Series/2223',
'NASCAR.ARCA.Series': 'J:/Sportss/NASCAR ARCA Series/2223',
'Scottish.Highland.League': 'J:/Sportss/Scottish Highland League/2223',
'Scottish.Lowland.League': 'J:/Sportss/Scottish Lowland League/2223',
'Northern.Irish.Premier.Intermediate.League': 'J:/Sportss/Northern Irish Premier Intermediate League/2223',
'Dutch.Tweede.Divisie': 'J:/Sportss/Dutch Tweede Divisie/2223',
'Welsh.League.Cup': 'J:/Sportss/Welsh League Cup/2223',
'ICC.World.Test.Championship': 'J:/Sportss/ICC World Test Championship/2223',
'Womens.Cricket.World.Cup': 'J:/Sportss/Womens Cricket World Cup/2223',
'ICC.Mens.T20.World.Cup': 'J:/Sportss/ICC Mens T20 World Cup/2223',
'ICC.Womens.T20.World.Cup': 'J:/Sportss/ICC Womens T20 World Cup/2223',
'FIFA.Arab.Cup': 'J:/Sportss/FIFA Arab Cup/2223',
'Spanish.Primera.División.Women': 'J:/Sportss/Spanish Primera División Women/2223',
'Australian.Baseball.League': 'J:/Sportss/Australian Baseball League/2223',
'Cuban.National.Series': 'J:/Sportss/Cuban National Series/2223',
'Mexican.Pacific.League': 'J:/Sportss/Mexican Pacific League/2223',
'Honkbal.Hoofdklasse': 'J:/Sportss/Honkbal Hoofdklasse/2223',
'Chinese.Professional.Baseball.League': 'J:/Sportss/Chinese Professional Baseball League/2223',
'Venezuelan.Professional.Baseball.League': 'J:/Sportss/Venezuelan Professional Baseball League/2223',
'Australian.WNBL': 'J:/Sportss/Australian WNBL/2223',
'Danish.Basketligaen': 'J:/Sportss/Danish Basketligaen/2223',
'Estonian.Korvpalli.Meistriliiga': 'J:/Sportss/Estonian Korvpalli Meistriliiga/2223',
'Finnish.Korisliiga': 'J:/Sportss/Finnish Korisliiga/2223',
'Kosovo.Basketball.Superleague': 'J:/Sportss/Kosovo Basketball Superleague/2223',
'Mexican.LNBP': 'J:/Sportss/Mexican LNBP/2223',
'Macedonian.Superleague': 'J:/Sportss/Macedonian Superleague/2223',
'Basketball.League.of.Serbia': 'J:/Sportss/Basketball League of Serbia/2223',
'Slovak.Basketball.League': 'J:/Sportss/Slovak Basketball League/2223',
'Slovenian.Liga.Nova.KBM': 'J:/Sportss/Slovenian Liga Nova KBM/2223',
'Korean.Basketball.League': 'J:/Sportss/Korean Basketball League/2223',
'Swiss.SB.League': 'J:/Sportss/Swiss SB League/2223',
'Ukrainian.Basketball.SuperLeague': 'J:/Sportss/Ukrainian Basketball SuperLeague/2223',
'Womens.British.Basketball.League': 'J:/Sportss/Womens British Basketball League/2223',
'Bulgarian.NBL': 'J:/Sportss/Bulgarian NBL/2223',
'Cyprus.Basketball.Division.A': 'J:/Sportss/Cyprus Basketball Division A/2223',
'Basketball.Championship.of.Bosnia.and.Herzegovina': 'J:/Sportss/Basketball Championship of Bosnia and Herzegovina/2223',
'Chinese.WCBA': 'J:/Sportss/Chinese WCBA/2223',
'German.ProA': 'J:/Sportss/German ProA/2223',
'Lithuanian.NKL': 'J:/Sportss/Lithuanian NKL/2223',
'Spanish.LEB.Oro': 'J:/Sportss/Spanish LEB Oro/2223',
'Danish.Mens.Handball.League': 'J:/Sportss/Danish Mens Handball League/2223',
'Swedish.Handbollsligan': 'J:/Sportss/Swedish Handbollsligan/2223',
'Olympics.Ice.Hockey': 'J:/Sportss/Olympics Ice Hockey/2223',
'Olympics.Alpine.Skiing': 'J:/Sportss/Olympics Alpine Skiing/2223',
'Olympics.Biathlon': 'J:/Sportss/Olympics Biathlon/2223',
'Olympics.Cross-country.Skiing': 'J:/Sportss/Olympics Cross-country Skiing/2223',
'Olympics.Freestyle.Skiing': 'J:/Sportss/Olympics Freestyle Skiing/2223',
'Olympics.Nordic.Combined': 'J:/Sportss/Olympics Nordic Combined/2223',
'Olympics.Ski.Jumping': 'J:/Sportss/Olympics Ski Jumping/2223',
'Olympics.Snowboarding': 'J:/Sportss/Olympics Snowboarding/2223',
'Olympics.Figure.Skating': 'J:/Sportss/Olympics Figure Skating/2223',
'Olympics.Short.Track.Speed.Skating': 'J:/Sportss/Olympics Short Track Speed Skating/2223',
'Olympics.Speed.Skating': 'J:/Sportss/Olympics Speed Skating/2223',
'Olympics.Bobsleigh': 'J:/Sportss/Olympics Bobsleigh/2223',
'Olympics.Skeleton': 'J:/Sportss/Olympics Skeleton/2223',
'Olympics.Curling': 'J:/Sportss/Olympics Curling/2223',
'Olympics.Luge': 'J:/Sportss/Olympics Luge/2223',
'Ice.Hockey.All-Star.Games': 'J:/Sportss/Ice Hockey All-Star Games/2223',
'Basketball.All-Star.Games': 'J:/Sportss/Basketball All-Star Games/2223',
'American.Football.All-Star.Games': 'J:/Sportss/American Football All-Star Games/2223',
'Estonian.Hokiliiga': 'J:/Sportss/Estonian Hokiliiga/2223',
'Hungarian.Erste.Liga': 'J:/Sportss/Hungarian Erste Liga/2223',
'American.Premier.Hockey.Federation': 'J:/Sportss/American Premier Hockey Federation/2223',
'Swedish.Womens.Hockey.League': 'J:/Sportss/Swedish Womens Hockey League/2223',
'Canadian.OHL': 'J:/Sportss/Canadian OHL/2223',
'Canadian.WHL': 'J:/Sportss/Canadian WHL/2223',
'Canadian.QMJHL': 'J:/Sportss/Canadian QMJHL/2223',
'Swedish.Hockey.Allsvenskan': 'J:/Sportss/Swedish Hockey Allsvenskan/2223',
'Swiss.League': 'J:/Sportss/Swiss League/2223',
'American.SPHL': 'J:/Sportss/American SPHL/2223',
'URBA.Top.13': 'J:/Sportss/URBA Top 13/2223',
'English.Premier.15s': 'J:/Sportss/English Premier 15s/2223',
'Japan.Rugby.League.One': 'J:/Sportss/Japan Rugby League One/2223',
'Romanian.SuperLiga': 'J:/Sportss/Romanian SuperLiga/2223',
'Super.Liga.Americana': 'J:/Sportss/Super Liga Americana/2223',
'Spanish.División.de.Honor': 'J:/Sportss/Spanish División de Honor/2223',
'Australian.Shute.Shield': 'J:/Sportss/Australian Shute Shield/2223',
'French.Pro.D2': 'J:/Sportss/French Pro D2/2223',
'Scottish.Premiership': 'J:/Sportss/Scottish Premiership/2223',
'New.Zealand.Super.Smash': 'J:/Sportss/New Zealand Super Smash/2223',
'Lanka.Premier.League': 'J:/Sportss/Lanka Premier League/2223',
'Caribbean.Premier.League': 'J:/Sportss/Caribbean Premier League/2223',
'The.Hundred': 'J:/Sportss/The Hundred/2223',
'American.NWSL.Challenge.Cup': 'J:/Sportss/American NWSL Challenge Cup/2223',
'Asian.Cup.Women': 'J:/Sportss/Asian Cup Women/2223',
'Australia.FFA.Cup': 'J:/Sportss/Australia FFA Cup/2223',
'CECAFA.Club.Cup': 'J:/Sportss/CECAFA Club Cup/2223',
'COSAFA.Cup': 'J:/Sportss/COSAFA Cup/2223',
'Copa.Colombia': 'J:/Sportss/Copa Colombia/2223',
'Denmark.DBU.Pokalen': 'J:/Sportss/Denmark DBU Pokalen/2223',
'Egypt.League.Cup': 'J:/Sportss/Egypt League Cup/2223',
'Finnish.Cup': 'J:/Sportss/Finnish Cup/2223',
'Italy.Coppa.Italia.Serie.C': 'J:/Sportss/Italy Coppa Italia Serie C/2223',
'Japanese.JLeague.Cup': 'J:/Sportss/Japanese JLeague Cup/2223',
'Kuwait.Crown.Prince.Cup': 'J:/Sportss/Kuwait Crown Prince Cup/2223',
'Kuwait.Emir.Cup': 'J:/Sportss/Kuwait Emir Cup/2223',
'Malaysia.Cup': 'J:/Sportss/Malaysia Cup/2223',
'Qatar.QSL.Cup': 'J:/Sportss/Qatar QSL Cup/2223',
'Russia.Cup': 'J:/Sportss/Russia Cup/2223',
'SAFF.Championship': 'J:/Sportss/SAFF Championship/2223',
'San.Marino.Coppa.Titano': 'J:/Sportss/San Marino Coppa Titano/2223',
'Slovenia.Cup': 'J:/Sportss/Slovenia Cup/2223',
'South-Africa.8.Cup': 'J:/Sportss/South-Africa 8 Cup/2223',
'UAE.League.Cup': 'J:/Sportss/UAE League Cup/2223',
'US.Open.Cup': 'J:/Sportss/US Open Cup/2223',
'Vietnamese.Cup': 'J:/Sportss/Vietnamese Cup/2223',
'Brazil.Brasileiro.Women': 'J:/Sportss/Brazil Brasileiro Women/2223',
'Denmark.Elitedivisionen': 'J:/Sportss/Denmark Elitedivisionen/2223',
'France.Feminine.Division.1': 'J:/Sportss/France Feminine Division 1/2223',
'Germany.Women.Bundesliga': 'J:/Sportss/Germany Women Bundesliga/2223',
'Italy.Serie.A.Women': 'J:/Sportss/Italy Serie A Women/2223',
'Mexico.Liga.MX.Femenil': 'J:/Sportss/Mexico Liga MX Femenil/2223',
'Netherlands.Eredivisie.Women': 'J:/Sportss/Netherlands Eredivisie Women/2223',
'Norway.Toppserien': 'J:/Sportss/Norway Toppserien/2223',
'Sweden.Damallsvenskan': 'J:/Sportss/Sweden Damallsvenskan/2223',
'Taiwan.Football.Premier.League': 'J:/Sportss/Taiwan Football Premier League/2223',
'Zambia.Super.League': 'J:/Sportss/Zambia Super League/2223',
'England.Womens.Championship': 'J:/Sportss/England Womens Championship/2223',
'Kuwait.Division.1': 'J:/Sportss/Kuwait Division 1/2223',
'Vietnam.V.League.2': 'J:/Sportss/Vietnam V League 2/2223',
'Argentina.Primera.B.Metropolitana': 'J:/Sportss/Argentina Primera B Metropolitana/2223',
'Portugal.Liga.3': 'J:/Sportss/Portugal Liga 3/2223',
'Russia.FNL.2.Group.1': 'J:/Sportss/Russia FNL 2 Group 1/2223',
'Russia.FNL.2.Group.2': 'J:/Sportss/Russia FNL 2 Group 2/2223',
'Russia.FNL.2.Group.3': 'J:/Sportss/Russia FNL 2 Group 3/2223',
'Russia.FNL.2.Group.4': 'J:/Sportss/Russia FNL 2 Group 4/2223',
'USA.NISA': 'J:/Sportss/USA NISA/2223',
'Denmark.3.Division': 'J:/Sportss/Denmark 3 Division/2223',
'Netherlands.Derde.Divisie.Saturday': 'J:/Sportss/Netherlands Derde Divisie Saturday/2223',
'Netherlands.Derde.Divisie.Sunday': 'J:/Sportss/Netherlands Derde Divisie Sunday/2223',
'England.Non.League.Div.One.Isthmian.North': 'J:/Sportss/England Non League Div One Isthmian North/2223',
'England.Non.League.Div.One.Isthmian.South': 'J:/Sportss/England Non League Div One Isthmian South/2223',
'England.Non.League.Div.One.Southern.SW': 'J:/Sportss/England Non League Div One Southern SW/2223',
'England.Non.League.Div.One.Southern.Central': 'J:/Sportss/England Non League Div One Southern Central/2223',
'Angolan.Girabola': 'J:/Sportss/Angolan Girabola/2223',
'Aruban.Division.di.Honor': 'J:/Sportss/Aruban Division di Honor/2223',
'Benin.Championnat.National': 'J:/Sportss/Benin Championnat National/2223',
'Bermuda.Premier.League': 'J:/Sportss/Bermuda Premier League/2223',
'Botswana.Premier.League': 'J:/Sportss/Botswana Premier League/2223',
'Burkina.Faso.1ere.Division': 'J:/Sportss/Burkina Faso 1ere Division/2223',
'Burundi.Ligue.A': 'J:/Sportss/Burundi Ligue A/2223',
'Eswatini.Premier.League': 'J:/Sportss/Eswatini Premier League/2223',
'Gambia.GFA.League': 'J:/Sportss/Gambia GFA League/2223',
'Guadeloupe.Division.dHonneur': 'J:/Sportss/Guadeloupe Division dHonneur/2223',
'Guinea.Ligue.1': 'J:/Sportss/Guinea Ligue 1/2223',
'Ivory.Coast.Ligue.1': 'J:/Sportss/Ivory Coast Ligue 1/2223',
'Lebanon.Premier.League': 'J:/Sportss/Lebanon Premier League/2223',
'Liberian.LFA.First.Division': 'J:/Sportss/Liberian LFA First Division/2223',
'Libyan.Premier.League': 'J:/Sportss/Libyan Premier League/2223',
'Maldives.Dhivehi.Premier.League': 'J:/Sportss/Maldives Dhivehi Premier League/2223',
'Mauritania.Premier.League': 'J:/Sportss/Mauritania Premier League/2223',
'Mongolian.Premier.League': 'J:/Sportss/Mongolian Premier League/2223',
'Nepalese.A.Division': 'J:/Sportss/Nepalese A Division/2223',
'Oman.Professional.League': 'J:/Sportss/Oman Professional League/2223',
'Pakistan.Premier.League': 'J:/Sportss/Pakistan Premier League/2223',
'Palestinian.West.Bank.Premier.League': 'J:/Sportss/Palestinian West Bank Premier League/2223',
'Rwandan.National.Soccer.League': 'J:/Sportss/Rwandan National Soccer League/2223',
'Somali.Premier.League': 'J:/Sportss/Somali Premier League/2223',
'Sudani.Premier.League': 'J:/Sportss/Sudani Premier League/2223',
'Syrian.Premier.League': 'J:/Sportss/Syrian Premier League/2223',
'Turkmenistan.Yokary.Liga': 'J:/Sportss/Turkmenistan Yokary Liga/2223',
'Ugandan.Premier.League': 'J:/Sportss/Ugandan Premier League/2223',
'Zimbabwe.Premier.Soccer.League': 'J:/Sportss/Zimbabwe Premier Soccer League/2223',
'United.States.Football.League': 'J:/Sportss/United States Football League/2223',
'SheBelieves.Cup': 'J:/Sportss/SheBelieves Cup/2223',
'British.Superbike.Championship': 'J:/Sportss/British Superbike Championship/2223',
'Austrian.Basketball.Superliga': 'J:/Sportss/Austrian Basketball Superliga/2223',
'Canadian.Elite.Basketball.League': 'J:/Sportss/Canadian Elite Basketball League/2223',
'Taiwan.SBL': 'J:/Sportss/Taiwan SBL/2223',
'Vietnam.Basketball.Association': 'J:/Sportss/Vietnam Basketball Association/2223',
'Basketball.Africa.League': 'J:/Sportss/Basketball Africa League/2223',
'BNXT.League': 'J:/Sportss/BNXT League/2223',
'Israeli.Basketball.National.League': 'J:/Sportss/Israeli Basketball National League/2223',
'NIT': 'J:/Sportss/NIT/Season 2023',
'Basketball.Champions.League.Americas': 'J:/Sportss/Basketball Champions League Americas/2223',
'Womens.EHF.Champions.League': 'J:/Sportss/Womens EHF Champions League/2223',
'EHF.European.League': 'J:/Sportss/EHF European League/2223',
'BeNe.League': 'J:/Sportss/BeNe League/2223',
'Champions.Hockey.League': 'J:/Sportss/Champions Hockey League/2223',
'National.Provincial.Championship': 'J:/Sportss/National Provincial Championship/2223',
'MLS.Next.Pro': 'J:/Sportss/MLS Next Pro/2223',
'CONCACAF.Nations.League': 'J:/Sportss/CONCACAF Nations League/2223',
'Leagues.Cup': 'J:/Sportss/Leagues Cup/2223',
'Diamond.League': 'J:/Sportss/Diamond League/2223',
'World.Athletics.Indoor.Championships': 'J:/Sportss/World Athletics Indoor Championships/2223',
'Pan.American.Games.Athletics': 'J:/Sportss/Pan American Games Athletics/2223',
'European.Athletics.Championships': 'J:/Sportss/European Athletics Championships/2223',
'European.Athletics.Indoor.Championships': 'J:/Sportss/European Athletics Indoor Championships/2223',
'Asian.Games.Athletics': 'J:/Sportss/Asian Games Athletics/2223',
'Dragon.Gate': 'J:/Sportss/Dragon Gate/2223',
'DDT.Pro': 'J:/Sportss/DDT Pro/2223',
'RevPro': 'J:/Sportss/RevPro/Season 2023',
'ICW': 'J:/Sportss/ICW/Season 2023',
'wXw': 'J:/Sportss/wXw/Season 2023',
'Stardom': 'J:/Sportss/Stardom/Season 2023',
'TJPW': 'J:/Sportss/TJPW/Season 2023',
'Gatoh.Move': 'J:/Sportss/Gatoh Move/2223',
'Ice.Ribbon': 'J:/Sportss/Ice Ribbon/2223',
'Sendai.Girls': 'J:/Sportss/Sendai Girls/2223',
'SEAdLINNNG': 'J:/Sportss/SEAdLINNNG/Season 2023',
'SHIMMER': 'J:/Sportss/SHIMMER/Season 2023',
'CYN': 'J:/Sportss/CYN/Season 2023',
'Dragon.Gate.USA': 'J:/Sportss/Dragon Gate USA/2223',
'World.Athletics.Continental.Tour.Gold': 'J:/Sportss/World Athletics Continental Tour Gold/2223',
'World.Athletics.Continental.Tour.Silver': 'J:/Sportss/World Athletics Continental Tour Silver/2223',
'World.Athletics.Continental.Tour.Bronze': 'J:/Sportss/World Athletics Continental Tour Bronze/2223',
'World.Athletics.Relays': 'J:/Sportss/World Athletics Relays/2223',
'SRX': 'J:/Sportss/SRX/Season 2023',
'_Defunct.Athletics.Teams': 'J:/Sportss/_Defunct Athletics Teams/2223',
'World.Swimming.Championships': 'J:/Sportss/World Swimming Championships/2223',
'NHRA.Drag.Racing': 'J:/Sportss/NHRA Drag Racing/2223',
'China.league.Two': 'J:/Sportss/China league Two/2223',
'AFL.Womens': 'J:/Sportss/AFL Womens/2223',
'UCI.Womens.World.Tour': 'J:/Sportss/UCI Womens World Tour/2223',
'Slovenian.2.SNL': 'J:/Sportss/Slovenian 2 SNL/2223',
'Slovakian.2.Liga': 'J:/Sportss/Slovakian 2 Liga/2223',
'Welsh.Cymru.North-South': 'J:/Sportss/Welsh Cymru North-South/2223',
'Austrian.Regionalliga.West': 'J:/Sportss/Austrian Regionalliga West/2223',
'Austrian.Regionalliga.Ost': 'J:/Sportss/Austrian Regionalliga Ost/2223',
'Austrian.Regionalliga.Mitte': 'J:/Sportss/Austrian Regionalliga Mitte/2223',
'Swiss.Promotion.League': 'J:/Sportss/Swiss Promotion League/2223',
'French.National.2.Group.A': 'J:/Sportss/French National 2 Group A/2223',
'French.National.2.Group.B': 'J:/Sportss/French National 2 Group B/2223',
'French.National.2.Group.C': 'J:/Sportss/French National 2 Group C/2223',
'French.National.2.Group.D': 'J:/Sportss/French National 2 Group D/2223',
'English.Southern.Premier.League.Central.Division': 'J:/Sportss/English Southern Premier League Central Division/2223',
'English.Northern.Premier.League.Division.One.East': 'J:/Sportss/English Northern Premier League Division One East/2223',
'English.Northern.Premier.League.Division.One.Midlands': 'J:/Sportss/English Northern Premier League Division One Midlands/2223',
'English.Southern.Premier.League.Central.Division.One': 'J:/Sportss/English Southern Premier League Central Division One/2223',
'English.Northern.Premier.League.Division.One.West': 'J:/Sportss/English Northern Premier League Division One West/2223',
'LIV.Golf': 'J:/Sportss/LIV Golf/2223',
'UCI.ProSeries': 'J:/Sportss/UCI ProSeries/2223',
'UCI.Africa.Tour': 'J:/Sportss/UCI Africa Tour/2223',
'UCI.America.Tour': 'J:/Sportss/UCI America Tour/2223',
'UCI.Asia.Tour': 'J:/Sportss/UCI Asia Tour/2223',
'UCI.Europe.Tour': 'J:/Sportss/UCI Europe Tour/2223',
'UCI.Oceania.Tour': 'J:/Sportss/UCI Oceania Tour/2223',
'GFL': 'J:/Sportss/GFL/Season 2023',
'Premier.Lacrosse.League': 'J:/Sportss/Premier Lacrosse League/2223',
'National.Lacrosse.League': 'J:/Sportss/National Lacrosse League/2223',
'Italian.Serie.C.Girone.B': 'J:/Sportss/Italian Serie C Girone B/2223',
'Italian.Serie.C.Girone.A': 'J:/Sportss/Italian Serie C Girone A/2223',
'TKO.MMA': 'J:/Sportss/TKO MMA/2223',
'Biathlon.World.Cup': 'J:/Sportss/Biathlon World Cup/2223',
'Asian.Athletics.Championships': 'J:/Sportss/Asian Athletics Championships/2223',
'FIVB.Volleyball.Mens.World.Championship': 'J:/Sportss/FIVB Volleyball Mens World Championship/2223',
'FIVB.Volleyball.Womens.World.Championship': 'J:/Sportss/FIVB Volleyball Womens World Championship/2223',
'NCAA.Division.1.Ice.Hockey': 'J:/Sportss/NCAA Division 1 Ice Hockey/2223',
'Davis.Cup': 'J:/Sportss/Davis Cup/2223',
'Fed.Cup': 'J:/Sportss/Fed Cup/2223',
'Hopman.Cup': 'J:/Sportss/Hopman Cup/2223',
'U.Sports.Football.League': 'J:/Sportss/U Sports Football League/2223',
'NBL1.West': 'J:/Sportss/NBL1 West/2223',
'World.Swimming.Championships.SC': 'J:/Sportss/World Swimming Championships SC/2223',
'European.Swimming.Championships': 'J:/Sportss/European Swimming Championships/2223',
'European.Swimming.Championships.SC': 'J:/Sportss/European Swimming Championships SC/2223',
'Commonwealth.Games.Swimming': 'J:/Sportss/Commonwealth Games Swimming/2223',
'Commonwealth.Games.Diving': 'J:/Sportss/Commonwealth Games Diving/2223',
'Commonwealth.Games.Badminton': 'J:/Sportss/Commonwealth Games Badminton/2223',
'Commonwealth.Games.3x3.Basketball': 'J:/Sportss/Commonwealth Games 3x3 Basketball/2223',
'Commonwealth.Games.Beach.Volleyball': 'J:/Sportss/Commonwealth Games Beach Volleyball/2223',
'Commonwealth.Games.Boxing': 'J:/Sportss/Commonwealth Games Boxing/2223',
'Commonwealth.Games.Cricket': 'J:/Sportss/Commonwealth Games Cricket/2223',
'Commonwealth.Games.Mountain.Bike': 'J:/Sportss/Commonwealth Games Mountain Bike/2223',
'Commonwealth.Games.Road.Cycling': 'J:/Sportss/Commonwealth Games Road Cycling/2223',
'Commonwealth.Games.Track.Cycling': 'J:/Sportss/Commonwealth Games Track Cycling/2223',
'Commonwealth.Games.Artistic.Gymnastics': 'J:/Sportss/Commonwealth Games Artistic Gymnastics/2223',
'Commonwealth.Games.Rhythmic.Gymnastics': 'J:/Sportss/Commonwealth Games Rhythmic Gymnastics/2223',
'Commonwealth.Games.Field.Hockey': 'J:/Sportss/Commonwealth Games Field Hockey/2223',
'Commonwealth.Games.Judo': 'J:/Sportss/Commonwealth Games Judo/2223',
'Commonwealth.Games.Netball': 'J:/Sportss/Commonwealth Games Netball/2223',
'Commonwealth.Games.7s.Rugby': 'J:/Sportss/Commonwealth Games 7s Rugby/2223',
'Commonwealth.Games.Table.Tennis': 'J:/Sportss/Commonwealth Games Table Tennis/2223',
'Commonwealth.Games.Triathlon': 'J:/Sportss/Commonwealth Games Triathlon/2223',
'Commonwealth.Games.Weightlifting': 'J:/Sportss/Commonwealth Games Weightlifting/2223',
'Commonwealth.Games.Wrestling': 'J:/Sportss/Commonwealth Games Wrestling/2223',
'_Defunct.Watersports.Teams': 'J:/Sportss/_Defunct Watersports Teams/2223',
'International.Friendlies.Ice.Hockey': 'J:/Sportss/International Friendlies Ice Hockey/2223',
'Italian.Serie.A2': 'J:/Sportss/Italian Serie A2/2223',
'Copa.Chile': 'J:/Sportss/Copa Chile/2223',
'KOK': 'J:/Sportss/KOK/Season 2023'
}

def move_items(item_list, target_path, log):
    # Create the target directory if it doesn't exist
    if not os.path.exists(target_path):
        os.makedirs(target_path)
        time.sleep(0.15)

    for item in item_list:
        print(f"Moving {item} to {target_path}")
        target_file_path = os.path.join(target_path, os.path.basename(item))
        if os.path.exists(target_file_path):
            log.append([item, target_file_path, 'Duplicate', get_timestamp()])
        else:
            try:
                shutil.move(item, target_file_path)
                time.sleep(0.15)  # Add a 0.15-second delay after each move operation
                log.append([item, target_file_path, 'Success', get_timestamp()])
            except Exception as e:
                log.append([item, target_file_path, f"Error: {e}", get_timestamp()])

def find_items(path, league_list):
    item_list = []
    for root, _, files in os.walk(path):
        for file in files:
            if any(league in file for league in league_list) and file.endswith('.mkv'):
                item_list.append(os.path.join(root, file))
    return item_list

def get_timestamp():
    now = datetime.now()
    return now.strftime("%d-%m-%Y %H:%M:%S")

# Update the league names
league_list = ['English.Premier.League', 'English.League.Championship', 'Scottish.Premier.League', 'German.Bundesliga', 'Italian.Serie.A', 'French.Ligue.1', 'Spanish.La.Liga', 'Greek.Superleague.Greece', 'Dutch.Eredivisie', 'Belgian.First.Division.A', 'Turkish.Super.Lig', 'Danish.Superliga', 'Portuguese.Primeira.Liga', 'American.Major.League.Soccer', 'MLS', 'Swedish.Allsvenskan', 'Mexican.Primera.League', 'Brazilian.Serie.A', 'Ukrainian.Premier.League', 'Russian.Football.Premier.League', 'Australian.A-League', 'Norwegian.Eliteserien', 'Chinese.Super.League', '_No.League', 'Formula.1', 'Formula.E', 'BTCC', 'IndyCar.Series', 'NHL', 'UK.Elite.Ice.Hockey.League', 'NBA', 'NBA.G.League', 'NFL', 'NASCAR.Cup.Series', 'Italian.Serie.B', 'Scottish.Championship', 'English.League.1', 'English.League.2', 'Italian.Serie.C.Girone.C', 'German.2..Bundesliga', 'Spanish.La.Liga.2', 'French.Ligue.2', 'Swedish.Superettan', 'Brazilian.Serie.B', 'CFL', 'Argentinian.Primera.Division', 'MotoGP', 'Spanish.Liga.ACB', 'WRC', 'British.GT.Championship', 'WTCC', 'Super.GT.series', 'WEC', 'English.Premiership.Rugby', 'English.Rugby.League.Super.League', 'Australian.National.Rugby.League', 'Australian.National.Rugby.Championship', 'Swedish.Hockey.League', 'Polish.Ekstraklasa', 'French.LNB', 'MLB', 'PGA.Tour', 'European.Tour', 'Can-Am', 'Frontier.League', 'FIFA.World.Cup', 'French.Top.14', 'British.Basketball.League', 'Uruguayan.Primera.Division', 'Italian.Lega.Basket', 'Australian.NBL', 'American.NASL', 'Moto2', 'Moto3', 'DTM', 'GT.Series.Endurance.Cup', 'GT.World.Challenge.Europe.Sprint.Cup', 'German.BBL', 'Chinese.CBA', 'UFC', 'WWE', 'Boxing', 'United.Rugby.Championship', 'Dakar.Rally', 'ROH', 'NJPW', 'WCW', 'ECW', 'Greek.Basket.League', 'NWA', 'SBK', 'Impact.Wrestling', 'Australian.AFL', 'Norwegian.1..Divisjon', 'English.County.Championship.Division.1', 'English.County.Championship.Division.2', 'Indian.Premier.League', 'Australian.Big.Bash.League', 'South.African.T20.Challenge', 'English.t20.Blast', 'ATP.World.Tour', 'UCI.World.Tour', 'Electric.GT.Championship', 'Bellator', 'AMA.Supercross', 'Pro.Motocross', 'Arena.Football.League', 'Indoor.Football.League', 'Welsh.Premier.League', 'National.Arena.League', 'Israeli.Basketball.Premier.League', 'Turkish.Basketbol.Super.Ligi', 'Russian.VTB.United.League', 'Adriatic.ABA.League', 'Lithuanian.LKL', 'NCAA.Division.1', 'UEFA.Champions.League', 'UEFA.Europa.League', 'FA.Cup', 'Copa.del.Rey', 'Coupe.de.France', 'DFB-Pokal', 'Formula.2', 'Formula.3', 'IMSA.SportsCar.Championship', 'V8.Supercars', 'UEFA.Nations.League', 'Rizin.FF', 'Cage.Warriors', 'Invicta.FC', 'ACA', 'ONE', 'African.Cup.of.Nations', 'Colombia.Categoría.Primera.A', 'Confederations.Cup', 'Copa.America', 'Copa.Argentina', 'Copa.Libertadores', 'UEFA.European.Championships', 'FIFA.Club.World.Cup', 'Coupe.de.la.Ligue', 'International.Champions.Cup', 'Coppa.Italia', 'Supercoppa.Italiana', 'Taca.de.Liga', 'Taca.de.Portugal', 'Supercopa.de.Espana', 'UEFA.Super.Cup', 'Venezuela.Primera.Division', 'League.of.Legends.World.Championship', 'Fortnite', 'WNBA', 
'WTA.Tour', '_Defunct.Basketball.Teams', '_Defunct.Soccer.Teams', 'Moroccan.Championship', 'American.NWSL', '_Defunct.Motorsport.Teams', 'European.Cup', 'UEFA.Cup', 'Football.League.First.Division', 'Football.League.Super.Cup', 'League.of.Legends.Pro.League', 'League.of.Legends.Champions.Korea', 'League.of.Legends.European.Championship', 'League.of.Legends.Championship.Series', 'League.of.Legends.Master.Series', 'German.Handball-Bundesliga', 'Spanish.Liga.ASOBAL', 'Hungarian.Nemzeti.Bajnokság.I', 'French.LNH.Division.1', 'Polish.Handball.Superliga', 'New.Zealand.Netball.League', 'UK.Netball.Superleague', 'Australian.Super.Netball.League', '_Defunct.Netball.Teams', 'Greek.A1.Ethniki', 'Turkish.Volleyball.League', 'Italian.Volleyball.League', 'Russian.Volleyball.Super.League', 'EuroLeague.Basketball', 'EuroCup.Basketball', 'Basketball.Champions.League', 'FIBA.Basketball.World.Cup', 'European.Rugby.Champions.Cup', 'Super.Rugby', 'AAF', 'LPGA.Tour', 'PDC.Darts', 'World.Snooker', 'Mens.FIH.Pro.League', 'Euro.Hockey.League', 'Hockey.World.Cup', 'BDO.Darts', 'International.Friendlies', 'AEW', 'International.Race.of.Champions', 'FIFA.Womens.World.Cup', 'UEFA.European.Under-21.Championship', 'BKFC', 'FIFA.eWorld.Cup.Series', 'Club.Friendlies', 'EFL.Cup', 'FA.Community.Shield', 'NASCAR.Xfinity.Series', 'Rugby.World.Cup', 'Cricket.World.Cup', 'WTCR', 'French.LNB.Pro.B', 'Polish.Basketball.League', 'Belgian.PBL', 'Hungarian.Nemzeti.Bajnokság.IA', 'Laver.Cup', 'French.Ligue.A.Mens.Volleyball', 'French.Ligue.A.Womens.Volleyball', 'Italian.Womens.Volleyball.League', 'Olympics.Field.Hockey', 'MXGP', 'MotoE.World.Championship', 'English.RFL.Championship', 'English.National.League', 'Nippon.Baseball.League', '_Defunct.Baseball.Teams', 'AAA', 'AJPW', 'CMLL', 'NOAH', 'UWF', 'UWF-i', 'RINGS', 'Pancrase', 'DREAM', 'DEEP', 'IGF', 'Jungle.Fight', 'K-1', 'NCAA.Division.I.Basketball.Mens', 'Battlarts', 'BJW', 'BML', 'GCW', 'HUSTLE', 'PWFG', 'ZERO-1', 'Argentinian.Primera.B.Nacional', 'Albanian.Superliga', 'Andorran.1a.Divisió', 'Armenian.Premier.League', 'Australia.ACT.NPL', 'Austrian.Bundesliga', 'Belarus.Vyscha.Liga', 'Belgian.First.Division.B', 'Bosnian.Premier.Liga', 'Brazilian.Serie.C', 'Bulgarian.First.League', 'Chile.Primera.Division', 'China.League.One', 'Croatian.First.Football.League', 'Cypriot.First.Division', 'Czech.First.League', 'Danish.2nd.Division', 'Japanese.J1.League', 'Estonian.Meistriliiga', 'Faroe.Islands.Premier.League', 'Finish.Veikkausliiga', 'French.Championnat.National', 'Georgian.Erovnuli.Liga', 'Germany.Liga.3', 'Greek.Super.League.2', 'Dutch.Eerste.Divisie', 'Icelandic.Úrvalsdeild.karla', 'Irish.Premier.Division', 'Israeli.Premier.League', 'Italy.Serie.D.Girone.D', 'English.Northern.Premier.League.Premier.Division', 'English.Isthmian.League.Premier.Division', 'English.Southern.Premier.League.South.Division', 'Kazakhstan.Premier.League', 'Latvian.Higher.League', 'Lithuanian.A.Lyga', 'Macedonian.First.League', 'Maltese.Premier.League', 'Mexican.Ascenso.MX', 'Moldovan.National.Division', 'Montenegrin.First.League', 
'Moroccan.Botola.2', 'Northern.Irish.Premiership', 'Polish.I.liga', 'Portuguese.LigaPro', 'Qatar.Stars.League', 'Romanian.Liga.II', 'Russian.Football.National.League', 'San-Marino.Campionato', 'Saudi-Arabian.Pro.League', 'Scottish.League.1', 'Scottish.League.2', 'Serbian.Super.Liga', 'Slovakian.Super.Liga', 'Primera.División.RFEF.Group.1', 'Swedish.Division.1.North', 'Swiss.Super.League', 'Turkish.1.Lig', 'Ukrainian.First.League', 'UAE.Pro.League', 'Turkish.2.Lig', 'English.National.League.North', 'English.National.League.South', 'Danish.1st.Division', 'American.USL.Championship', 'Bolivian.Primera.División', 'Ecuadorian.Serie.A', 'Paraguayan.Primera.Division', 'Peruvian.Primera.Division', 'South.Korean.K.League.1', 'Hungarian.NB.I', 'Romanian.Liga.I', 'Slovenian.1..SNL', 'Azerbaijani.Premier.League', 'Luxembourg.National.Division', 'German.Regionalliga.Nord', 'Pride.FC', 'FREEDOMS', 'UFO', 'VTJ', 'World.Japan', 'U-STYLE', 'WAR', 'Michinoku.Pro', 'KINGDOM', 'AJW', 'W-1', 'Zona.23', 'KSW', 'WLC', 'Sumo', 'Extreme.E', 'Swiss.Challenge.League', 'Six.Nations.Championship', 'Call.of.Duty.League', 'Call.of.Duty.World.League', 'Overwatch.League', 'XFL', 'AFC.Champions.League', 'CAF.Champions.League', 'CONCACAF.Champions.League', 'English.RFU.Championship', 'Scottish.FA.Cup', 'Copa.Sudamericana', 'Copa.do.Brasil', 'Professional.Wrestling', 'Mixed.Martial.Arts', 'Diamond.Ring', 'SRC', 'World.Rallycross.Championship', 'Isle.of.Man.TT', 'Argentine.LNB', 'Shoot.Boxing', 'Shooto', 'RISE', 'American.AHL', 'CONCACAF.League', 'South.African.Sunshine.Tour', 'Iranian.Azadegan.League', 'Iranian.Persian.Gulf.Pro.League', 'Thai.Premier.League', 'Thai.League.2', 'Kenyan.Premier.League', 'German.Regionalliga.West', 'German.Regionalliga.SudWest', 'German.Regionalliga.Bayern', 'German.Regionalliga.Nordost', 'Primera.División.RFEF.Group.2', 'Spanish.Segunda.División.B.Group.3', 'Spanish.Segunda.División.B.Group.4', 'Algerian.Ligue.1', 'Senegal.Ligue.1', 'Northern.Irish.Championship', 'Svenska.Cupen', 'Irish.First.Division', 'European.Challenge.Tour', 'China.Tour', 'Japan.Golf.Tour', 'PGA.Tour.of.Australasia', 'Asian.Tour', 'Korn.Ferry.Tour', 'PGA.Tour.Latinoamérica', 'PGA.Tour.Canada', 'Korean.Tour', 'Asian.Development.Tour', 'Alps.Tour', 'Nordic.Golf.League', 'PGA.EuroPro.Tour', 'ProGolf.Tour', 'MENA.Golf.Tour', 'Big.Easy.Tour', 'PGA.Tour.China', 'All.Thailand.Golf.Tour', 'Professional.Golf.Tour.of.India', 'Japan.Challenge.Tour', 'Italy.Serie.D.Girone.B', 'Italy.Serie.D.Girone.C', 'Italy.Serie.D.Girone.E', 'Italy.Serie.D.Girone.F', 'Italy.Serie.D.Girone.G', 'Italy.Serie.D.Girone.H', 'Italy.Serie.D.Girone.I', 'Italy.Serie.D.Girone.A', 'Kickboxing', 'FA.Trophy', 'Malaysian.Premier.League', 'Indonesian.Super.League', 'Indian.Super.League', 'Malaysian.Super.League', 'Cambodia.C-League', 'Uzbekistan.Super.League', 'Singapore.Premier.League', 'Austrian.Erste.Liga', 'Indian.I-League', 'Glory', 'Affliction', 'Strikeforce', 'One.Day.International.Series', 'South.African.Premier.Soccer.League', 'Vietnamese.V.League.1', 'AFC.Cup', 'Australian.A-League.Women', 
'Nicaragua.Primera.Division', 'Heros', '_Defunct.Cricket.Teams', '_Defunct.American.Football.Teams', '_Defunct.Ice.Hockey.Teams', 'Tajikistan.Vysshaya.Liga', 'Belarusian.First.League', 'Belarus.Coppa', 'New-Zealand.Football.Championship', 'Costa-Rica.Liga.FPD', 'El.Salvador.Primera.Division', 'Guatemala.Liga.Nacional', 'Honduras.Liga.Nacional.de.Futbol', 'Panama.Liga.Panamena.de.Futbol', 'Canadian.Premier.League', 'Indian.I-League.2nd.Division', 'South.Korean.K.League.2', 'Kuwait.Premier.League', 'Japanese.J2.League', 'Hong-Kong.Premier.League', 'Bahrain.Premier.League', 'Nigerian.NPFL', 'Tunisian.Ligue.1', 'Egyptian.Premier.League', 'Korean.KBO.League', 'FIBA.EuroBasket', 'Spanish.Copa.del.Rey.de.Baloncesto', 'Spanish.Supercup.of.Basketball', '_No.League.Soccer', '_No.League.Motorsports', '_No.League.Basketball', '_No.League.Baseball', '_No.League.Ice.Hockey', '_No.League.American.Football', '_No.League.Fighting', '_No.League.Cricket', '_No.League.Netball', 'ILFJ', 'International.Test.Match.Series', 'Swedish.Division.1.South', 'GLEAT', 'EFL.Trophy', 'Jaguar.I-Pace.eTrophy', 'English.Womens.Super.League', 'FIBA.AmeriCup', '_Defunct.Cycling.Teams', 'ADCC', 'Quintet.', 'RJPW', 'KOPW', 'Riki.Pro', 'Dradition', 'SWS', 'IFL', 'ZST', 'Its.Showtime', 'KO', 'PGA.Tour.Champions', 'UEFA.Womens.Euro', 'AFC.Asian.Cup', 'OFC.Nations.Cup', 'IMSA.Prototype.Challenge.Series', 'IMSA.Pilot.Challenge', 'Porsche.GT3.Cup.Challenge', 'Lamborghini.Super.Trofeo.North.America', 'Ferrari.Challenge.North.America', 'CONCACAF.Gold.Cup', 'eNASCAR.iRacing.Series', 'Top.Rank', 'AJKF', 'KJP', 'TPW', 'USWF', 'KOTC', 'EliteXC', 'NCAA.Fighting', 'World.Extreme.Cagefighting', 'Spanish.Segunda.División.B.Group.5', 'FA.Womens.League.Cup', 'Scottish.League.Cup', 'UEFA.Womens.Champions.League', 'EuroBasket.Women', 'FIBA.Womens.World.Cup', 'EuroLeague.Women', 'European.Womens.Handball.Championship', 'European.Mens.Handball.Championship', 'World.Mens.Handball.Championship', 'World.Womens.Handball.Championship', 'FIBA.AfroBasket', 'FIBA.Asia.Cup', 'Chile.Primera.B', 'Paraguayan.División.Intermedia', 'French.Trophée.des.Champions', 'Dutch.KNVB.Cup', 'German.Super.Cup', 'Andorran.Segona.Divisió', 'Andorran.Cup', 'Icelandic.1.deild.karla', 'Albanian.Kategoria.e.Parë', 'Armenian.First.League', 'Armenian.Cup', 'Bolivian.Nacional.B.Copa.Simón.Bolívar', 'Bosnian.First.League', 'Bosnian.First.League.of.Srpska', 'Bulgarian.Second.League', 'Azerbaijan.First.Division', 'Azerbaijan.Cup', 'American.ECHL', 'American.USHL', 'American.FPHL', 'Russian.VHL', 'Russian.KHL', 'Latvian.Optibet.Hockey.League', 'Ukrainian.UHL', 'Czech.Extraliga', 'Belarusian.Extraleague', 'German.DEL', 'Norwegian.Fjordkraft-ligaen', 'French.Ligue.Magnus', 'Polish.Hockey.League', 'Slovak.Hockey.League', 'Danish.Metal.Ligaen', 'Finnish.Liiga', 'Slovak.Extraliga', 'Austrian.ICE.Hockey.League', 'Swiss.National.League', 'Finnish.Mestis', 'German.DEL.2', 'IVC', 'Meca', 'Colombian.Categoría.Primera.B', 'Croatian.Druga.HNL', 'Cypriot.Second.Division', 'Czech.National.Football.League', 'DR.Congo.Ligue.1', 
'Dominican.LDF', 'United.States.Football.League', 'Ecuadorian.Serie.B', 'Estonian.Esiliiga', 'Ethiopian.Premier.League', 'Turkish.Cup', 'Faroe.Islands.1..deild', 'Fijian.Premier.League', 'Finnish.Ykkönen', 'Gibraltarian.National.League', 'Hungarian.NB.II', 'Israeli.Liga.Leumit', 'Japanese.J3.League', 'Kosovan.Superleague', 'Kyrgyz.Premier.League', 'Lao.Premier.League', 'Emir.of.Qatar.Cup', 'Liechtenstein.Cup', 'Georgian.Erovnuli.Liga.2', 'Ghanaian.Premier.League', 'Olympic.Games', 'Mens.Ice.Hockey.World.Championships', 'Japanese.B1.League', 'AAW.Pro', 'Twenty20.International.Series', 'EHF.Champions.League', 'North.American.Rugby.League', 'FIBA.Womens.AmeriCup', 'Rugby.Europe.Championship', 'Autumn.Nations.Cup', 'Pacific.Nations.Cup', 'Rugby.Championship', 'AIW.Wrestling', 'CHIKARA.Pro', 'Combat.Zone.Wrestling', 'EVOLVE.Wrestling', 'MLW', 'PROGRESS.Wrestling', 'Pro.Wrestling.Guerrilla', 'Olympics.Athletics', 'Olympics.Badminton', 'Olympics.Climbing', 'Olympics.Equestrian', 'Olympics.Fencing', 'Olympics.Shooting', 'Olympics.Table.Tennis', 'Olympics.Modern.Pentathlon', 'Olympics.Weightlifting', 'World.Athletics.Championships', 'Commonwealth.Games.Athletics', 'Olympics.Skateboarding', 'Australia.Northern.NSW.NPL', 'Australia.New.South.Wales.NPL', 'Australia.Victoria.NPL', 'Australia.Brisbane.Premier.League', 'Australia.Queensland.NPL', 'Australia.Western.Australia.NPL', 'Australia.South.Australia.NPL', 'Australia.Northern.Territory.Premier.League', 'Olympics.Baseball', 'Olympics.SoftBall', 'Olympics.Basketball', 'Olympics.3x3.Basketball', 'Olympics.Mountain.Bike', 'Olympics.BMX.Freestyle', 'Olympics.BMX.Racing', 'Olympics.Road.Cycling', 'Olympics.Track.Cycling', 'Olympics.Boxing', 'Olympics.Judo', 'Olympics.Karate', 'Olympics.Taekwondo', 'Olympics.Wrestling', 'Olympics.Golf', 'Olympics.Artistic.Gymnastics', 'Olympics.Rhythmic.Gymnastics', 'Olympics.Handball', 'Olympics.Triathlon', 'Olympics.7s.Rugby', 'Olympics.Archery', 'Olympics.Soccer', 'Olympics.Tennis', 'Olympics.Beach.Volleyball', 'Olympics.Volleyball', 'Olympics.Artistic.Swimming', 'Olympics.Canoe.Slalom', 'Olympics.Canoe.Sprint', 'Olympics.Diving', 'Olympics.Marathon.Swimming', 'Olympics.Rowing', 'Olympics.Sailing', 'Olympics.Surfing', 'Olympics.Swimming', 'Olympics.Trampoline', 'Olympics.Water.Polo', 'Australia.Tasmania.NPL', 'Jordanian.Pro.League', 'Iraqi.Premier.League', 'CAF.Confederation.Cup', 'House.of.Hardcore', 'Riptide.Wrestling', 'Bar.Wrestling', 'Frontier.Martial-Arts.Wrestling', 'European.League.of.Football', 'Liga.Mexicana.de.Béisbol', 'New.Zealand.NBL', 'Pakistan.Super.League', 'New.Zealand.Ice.Hockey.League', 'Currie.Cup', 'Major.League.Rugby', 'UEFA.Europa.Conference.League', 'Uruguayan.Segunda.División', 'Peruvian.Segunda.División', 'Serbian.Prva.Liga', 'Jamaican.Premier.League', 'USL.League.One', 'USL.League.Two', 'Bangladesh.Premier.League', 'Brazil.Serie.D', 'Taiwan.Mulan.Football.League', 'Lucha.Underground', 'Six.Nations.Under.20s.Championship', 'FIVB.Volleyball.Mens.Nations.League', 'FIVB.Volleyball.Womens.Nations.League', 
'Spanish.Primera.RFEF.Group.1', 'Spanish.Segunda.RFEF.Group.1', 'Spanish.Primera.RFEF.Group.2', 'Spanish.Segunda.RFEF.Group.2', 'Spanish.Segunda.RFEF.Group.3', 'Spanish.Segunda.RFEF.Group.4', 'Spanish.Segunda.RFEF.Group.5', 'NASCAR.Truck.Series', 'NASCAR.ARCA.Series', 'Scottish.Highland.League', 'Scottish.Lowland.League', 'Northern.Irish.Premier.Intermediate.League', 'Dutch.Tweede.Divisie', 'Welsh.League.Cup', 'ICC.World.Test.Championship', 'Womens.Cricket.World.Cup', 'ICC.Mens.T20.World.Cup', 'ICC.Womens.T20.World.Cup', 'FIFA.Arab.Cup', 'Spanish.Primera.División.Women', 'Australian.Baseball.League', 'Cuban.National.Series', 'Mexican.Pacific.League', 'Honkbal.Hoofdklasse', 'Chinese.Professional.Baseball.League', 'Venezuelan.Professional.Baseball.League', 'Australian.WNBL', 'Danish.Basketligaen', 'Estonian.Korvpalli.Meistriliiga', 'Finnish.Korisliiga', 'Icelandic.Úrvalsdeild.karla', 'Kosovo.Basketball.Superleague', 'Mexican.LNBP', 'Macedonian.Superleague', 'Basketball.League.of.Serbia', 'Slovak.Basketball.League', 'Slovenian.Liga.Nova.KBM', 'Korean.Basketball.League', 'Swiss.SB.League', 'Ukrainian.Basketball.SuperLeague', 'Womens.British.Basketball.League', 'Bulgarian.NBL', 'Cyprus.Basketball.Division.A', 'Basketball.Championship.of.Bosnia.and.Herzegovina', 'Chinese.WCBA', 'German.ProA', 'Lithuanian.NKL', 'Spanish.LEB.Oro', 'Danish.Mens.Handball.League', 'Swedish.Handbollsligan', 'Olympics.Ice.Hockey', 'Olympics.Alpine.Skiing', 'Olympics.Biathlon', 'Olympics.Cross-country.Skiing', 'Olympics.Freestyle.Skiing', 'Olympics.Nordic.Combined', 'Olympics.Ski.Jumping', 'Olympics.Snowboarding', 'Olympics.Figure.Skating', 'Olympics.Short.Track.Speed.Skating', 'Olympics.Speed.Skating', 'Olympics.Bobsleigh', 'Olympics.Skeleton', 'Olympics.Curling', 'Olympics.Luge', 'Ice.Hockey.All-Star.Games', 'Basketball.All-Star.Games', 'American.Football.All-Star.Games', 'Estonian.Hokiliiga', 'Hungarian.Erste.Liga', 'American.Premier.Hockey.Federation', 'Swedish.Womens.Hockey.League', 'Canadian.OHL', 'Canadian.WHL', 'Canadian.QMJHL', 'Swedish.Hockey.Allsvenskan', 'Swiss.League', 'American.SPHL', 'URBA.Top.13', 'English.Premier.15s', 'Japan.Rugby.League.One', 'Romanian.SuperLiga', 'Super.Liga.Americana', 'Spanish.División.de.Honor', 'Australian.Shute.Shield', 'French.Pro.D2', 'Scottish.Premiership', 'New.Zealand.Super.Smash', 'Lanka.Premier.League', 'Caribbean.Premier.League', 'The.Hundred', 'American.NWSL.Challenge.Cup', 'Asian.Cup.Women', 'Australia.FFA.Cup', 'CECAFA.Club.Cup', 'COSAFA.Cup', 'Copa.Colombia', 'Denmark.DBU.Pokalen', 'Egypt.League.Cup', 'Finnish.Cup', 'Italy.Coppa.Italia.Serie.C', 'Japanese.JLeague.Cup', 'Kuwait.Crown.Prince.Cup', 'Kuwait.Emir.Cup', 'Malaysia.Cup', 'Qatar.QSL.Cup', 'Russia.Cup', 'SAFF.Championship', 'San.Marino.Coppa.Titano', 'Slovenia.Cup', 'South-Africa.8.Cup', 'UAE.League.Cup', 'US.Open.Cup', 'Vietnamese.Cup', 'Brazil.Brasileiro.Women', 'Denmark.Elitedivisionen', 'France.Feminine.Division.1', 'Germany.Women.Bundesliga', 'Italy.Serie.A.Women', 'Mexico.Liga.MX.Femenil', 'Netherlands.Eredivisie.Women', 
'Norway.Toppserien', 'Sweden.Damallsvenskan', 'Taiwan.Football.Premier.League', 'Zambia.Super.League', 'England.Womens.Championship', 'Kuwait.Division.1', 'Vietnam.V.League.2', 'Argentina.Primera.B.Metropolitana', 'Portugal.Liga.3', 'Russia.FNL.2.Group.1', 'Russia.FNL.2.Group.2', 'Russia.FNL.2.Group.3', 'Russia.FNL.2.Group.4', 'USA.NISA', 'Denmark.3.Division', 'Netherlands.Derde.Divisie.Saturday', 'Netherlands.Derde.Divisie.Sunday', 'England.Non.League.Div.One.Isthmian.North', 'England.Non.League.Div.One.Isthmian.South', 'England.Non.League.Div.One.Southern.SW', 'England.Non.League.Div.One.Southern.Central', 'Angolan.Girabola', 'Aruban.Division.di.Honor', 'Benin.Championnat.National', 'Bermuda.Premier.League', 'Botswana.Premier.League', 'Burkina.Faso.1ere.Division', 'Burundi.Ligue.A', 'Eswatini.Premier.League', 'Gambia.GFA.League', 'Guadeloupe.Division.dHonneur', 'Guinea.Ligue.1', 'Ivory.Coast.Ligue.1', 'Lebanon.Premier.League', 'Liberian.LFA.First.Division', 'Libyan.Premier.League', 'Maldives.Dhivehi.Premier.League', 'Mauritania.Premier.League', 'Mongolian.Premier.League', 'Nepalese.A.Division', 'Oman.Professional.League', 'Pakistan.Premier.League', 'Palestinian.West.Bank.Premier.League', 'Rwandan.National.Soccer.League', 'Somali.Premier.League', 'Sudani.Premier.League', 'Syrian.Premier.League', 'Turkmenistan.Yokary.Liga', 'Ugandan.Premier.League', 'Zimbabwe.Premier.Soccer.League', 'United.States.Football.League', 'SheBelieves.Cup', 'British.Superbike.Championship', 'Austrian.Basketball.Superliga', 'Canadian.Elite.Basketball.League', 'Taiwan.SBL', 'Vietnam.Basketball.Association', 'Basketball.Africa.League', 'BNXT.League', 'Israeli.Basketball.National.League', 'NIT', 'Basketball.Champions.League.Americas', 'Womens.EHF.Champions.League', 'EHF.European.League', 'BeNe.League', 'Champions.Hockey.League', 'National.Provincial.Championship', 'MLS.Next.Pro', 'CONCACAF.Nations.League', 'Leagues.Cup', 'Diamond.League', 'World.Athletics.Indoor.Championships', 'Pan.American.Games.Athletics', 'European.Athletics.Championships', 'European.Athletics.Indoor.Championships', 'Asian.Games.Athletics', 'Dragon.Gate', 'DDT.Pro', 'RevPro', 'ICW', 'wXw', 'Stardom', 'TJPW', 'Gatoh.Move', 'Ice.Ribbon', 'Sendai.Girls', 'SEAdLINNNG', 'SHIMMER', 'CYN', 'Dragon.Gate.USA', 'World.Athletics.Continental.Tour.Gold', 'World.Athletics.Continental.Tour.Silver', 'World.Athletics.Continental.Tour.Bronze', 'World.Athletics.Relays', 'SRX', '_Defunct.Athletics.Teams', 'World.Swimming.Championships', 'NHRA.Drag.Racing', 'China.league.Two', 'AFL.Womens', 'UCI.Womens.World.Tour', 'Slovenian.2.SNL', 'Slovakian.2.Liga', 'Welsh.Cymru.North-South', 'Austrian.Regionalliga.West', 'Austrian.Regionalliga.Ost', 'Austrian.Regionalliga.Mitte', 'Swiss.Promotion.League', 'French.National.2.Group.A', 'French.National.2.Group.B', 'French.National.2.Group.C', 'French.National.2.Group.D', 'English.Southern.Premier.League.Central.Division', 'English.Northern.Premier.League.Division.One.East', 'English.Northern.Premier.League.Division.One.Midlands', 
'English.Southern.Premier.League.Central.Division.One', 'English.Northern.Premier.League.Division.One.West', 'LIV.Golf', 'UCI.ProSeries', 'UCI.Africa.Tour', 'UCI.America.Tour', 'UCI.Asia.Tour', 'UCI.Europe.Tour', 'UCI.Oceania.Tour', 'GFL', 'Premier.Lacrosse.League', 'National.Lacrosse.League', 'Italian.Serie.C.Girone.B', 'Italian.Serie.C.Girone.A', 'TKO.MMA', 'Biathlon.World.Cup', 'Asian.Athletics.Championships', 'FIVB.Volleyball.Mens.World.Championship', 'FIVB.Volleyball.Womens.World.Championship', 'NCAA.Division.1.Ice.Hockey', 'Davis.Cup', 'Fed.Cup', 'Hopman.Cup', 'U.Sports.Football.League', 'NBL1.West', 'World.Swimming.Championships.SC', 'European.Swimming.Championships', 'European.Swimming.Championships.SC', 'Commonwealth.Games.Swimming', 'Commonwealth.Games.Diving', 'Commonwealth.Games.Badminton', 'Commonwealth.Games.3x3.Basketball', 'Commonwealth.Games.Beach.Volleyball', 'Commonwealth.Games.Boxing', 'Commonwealth.Games.Cricket', 'Commonwealth.Games.Mountain.Bike', 'Commonwealth.Games.Road.Cycling', 'Commonwealth.Games.Track.Cycling', 'Commonwealth.Games.Artistic.Gymnastics', 'Commonwealth.Games.Rhythmic.Gymnastics', 'Commonwealth.Games.Field.Hockey', 'Commonwealth.Games.Judo', 'Commonwealth.Games.Netball', 'Commonwealth.Games.7s.Rugby', 'Commonwealth.Games.Table.Tennis', 'Commonwealth.Games.Triathlon', 'Commonwealth.Games.Weightlifting', 'Commonwealth.Games.Wrestling', '_Defunct.Watersports.Teams', 'International.Friendlies.Ice.Hockey', 'Italian.Serie.A2']

items = find_items(media_directory, league_list)

log = []

required_leagues = set()

# Determine the required leagues based on files in media_directory
for item in items:
    for league in league_list:
        if league in item:
            required_leagues.add(league)
            break

# Option to create missing folders
if create_missing_folders:
    for league in destination_paths:
        if league not in required_leagues:
            path = destination_paths[league]
            os.makedirs(path, exist_ok=True)

# Move files to the respective destination folders
for league in required_leagues:
    matched_items = [item for item in items if league in item]
    print(f"{league} folders and .mkv files:", matched_items)
    move_items(matched_items, destination_paths[league], log)
    time.sleep(0.15)

# Save the log to an Excel file
log_filename = 'file_movement_log.xlsx'
wb = openpyxl.Workbook()
ws = wb.active
ws.append(['Status', 'Timestamp', 'Source File', 'Target File'])
for row in log:
    ws.append(row)
wb.save(log_filename)

print(f"File movement log saved to {log_filename}")

input("Press Enter to exit...")